### ISSUE TITLE
ESP in fullscreen mode? 

### ISSUE THREAD

**Issue by jwao** [TheFuckingRat/RatPoison#100]
I want to play with esp but don't want to put in fullscreen windowed to play the game, anyway to play with the overlay in fullscreen mode?
Because i want to use CSGO changer and when i use it the overlay just disappear.

**Comment by massi1234567** [comment]
Its not possible to use this kind of overlay in Fullscreen because it is an seperate window.

**Comment by jwao** [comment]
> Its not possible to use this kind of overlay in Fullscreen because it is an seperate window.

Its cause i was trying to use the Russian Skinchanger shit and when i click to load the overlay just stop working. Any idea? I'm downloading the jdk 12.0.2 to test if works.

**Comment by TheFuckingRat** [comment]
You cannot use the overlay drawn ontop of cs while in fullscreen, you can draw it on another application, but you'll have to alt tab regardless, if alt tabbing is slow disable focus assist while in game.
