### ISSUE TITLE
Builder doesn't work

### ISSUE THREAD

**Issue by 1337miro** [TheFuckingRat/RatPoison#101]
When running build.bat I get this error:

`> Task :compileKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_221' used by Gradle. Make sure Gradle is running on a JDK, not JRE.`

even though I have the correct JDK version installed

**Comment by TheFuckingRat** [comment]
Installing jdk 12 and setting it as java_home should work, info for this is near the bottom of the readme

**Comment by 1337miro** [comment]
Setting java_home in windows worked, thanks.

On another note, do you  happen to know why the default aimbot settings have such high FOV values? 60 fov for rifles isnt very legit.

**Comment by TheFuckingRat** [comment]
My current version (version that im working on, updated a bit from whats here atm) hasn't been touched very much and I find that the aim speed is incredibly slow and looks legit. This cheat is aimed towards being a legit cheat, you should be aiming normally and spraying as best you can and the aimbot will help correct your aim, so I don't think having a high FOV means a lot. The speed/smoothness/strictness is slow enough in my eyes to not even be questioned.

**Comment by 1337miro** [comment]
Alright, thanks. Closing the issue
