### ISSUE TITLE
Feature request: Model esp changes colour behind cover/in open

### ISSUE THREAD

**Issue by Jadax** [TheFuckingRat/RatPoison#102]
Would it be possible to get the player model esp to change colour behind cover and when in the open?

**Comment by TheFuckingRat** [comment]
This can be done using the only external vis check available which is bSpotted, the aimbot, bonetrigger and anything that requires a vis check uses it and can be somewhat slow. The fact that it's somewhat slow makes me question whether it's worth it, especially if you're relying on it to know when to shoot, I will add it to the todo as an option but no guarantee it will work fast enough for you or in general.

Close this issue whenever.
