### ISSUE TITLE
Black Screen when running RatPoision, can see boxESP and recoil crosshair, but cannot see game

### ISSUE THREAD

**Issue by YWnightmare** [TheFuckingRat/RatPoison#104]
Whenever I start RatPoison, both borderless and windowed, I get only a black screen as an overlay and the boxESP, recoil crosshair, and menu. I have tried disabling all ESP and I disabled bombtimer and spec list, but still only get a black screen. I am using JDK 12 as well, win10.

**Comment by TheFuckingRat** [comment]
Refer to https://github.com/TheFuckingRat/RatPoison/issues/83 if anything there doesn't help then theres nothing I can do

**Comment by YWnightmare** [comment]
I am running 1.8 apparently, even though I just installed 12 and set the JAVA_HOME to my java 12 folder, what else needs to be set to 12?

**Comment by TheFuckingRat** [comment]
Set JAVA_HOME, a guide telling you how is available from google and towards the end of the README
