### ISSUE TITLE
Any way to make the aim less locky?

### ISSUE THREAD

**Issue by mattbot101** [TheFuckingRat/RatPoison#105]
When up close, lock is blatant, so lately I just play without any aim assist on just RCS. But if I could set it to just slightly go towards the person far away and not lock on people when I jump and they're close.

**Comment by furioushell98** [comment]
I think the default settings are pretty legit. If you think the aim settings are blatant upclose then decrease Fov, increase smooth and aim strictness etc.

**Comment by mattbot101** [comment]
In one instance I jumped over the opponent and it seamlessly locked on as he went under me, no one called me out but from my end it looked super obvious. I’ll try those things, thanks.

**Comment by furioushell98** [comment]
I tried the cheat for a while and i get what you mean, you feel like the cheat is moving your view or something like that, everytime i was suspicious of something i would just go and watch the kill on demo later and i find it legit-looking, do that as well.

**Comment by mattbot101** [comment]
Thanks, will try.
