### ISSUE TITLE
Healthbar Width, Bomb Indicator section.

### ISSUE THREAD

**Issue by spy12085621** [TheFuckingRat/RatPoison#106]
This isn't all an issue but is there a way to make the indicator show the bomb not only when planted but also when dropped or when a T player has it? and when can I customize the healthbar width so it doesn't look that big? the height is fine.
No complaints about RatPoison other than the indicators sometiems do not show the right colors for other items and there's no nametag option. Solid work from you both for Charlatano and this.

**Comment by TheFuckingRat** [comment]
Healthbar width was adjusted, indicator esp and glow esp will now have a setting to show the bomb carrier. Will be available in the next update.
