### ISSUE TITLE
Blue screening anytime I try to run the cheat

### ISSUE THREAD

**Issue by mattbot101** [TheFuckingRat/RatPoison#107]
Worked fine yesterday, now it blue screens anytime I run the bat file. page file fault in non paged area or something. Is this just me? should I just rebuild the cheat and enter all my settings in again?

Edit: this time i got the cheat running and working but after less than 2 minutes I got a different error. “kernel security check failure” 

Edit 2: seems to not BSOD anymore, but now it crashes csgo constantly. Could it be the new update?

**Comment by TheFuckingRat** [comment]
I haven't had any issue with csgo crashing, are you using anything other than the default settings? If so provide a cfg if possible, the only issue I've ever had recently with crashing is while using indicator esp. From a quick search on kernel security check failure, it's typically from a memory/driver issue, or corrupted data.

**Comment by mattbot101** [comment]
I did sfc and another system file checker and no issues, and ram seems fine. Replacing it anyway.  Settings: https://files.catbox.moe/64m75z.7z

**Comment by mattbot101** [comment]
Damn, good thing I backed up my settings. My PC just died, so I reset it. Hopefully, no more BSOD.

**Comment by mattbot101** [comment]
This was an issue of my motherboard not fucking saving my settings, keeping an unstable overclock after I specifically chose no. Not an issue with Ratpoison. Closed.
