### ISSUE TITLE
HIGH CPU USAGE

### ISSUE THREAD

**Issue by phooooon** [TheFuckingRat/RatPoison#109]
Sometimes i play on my laptop when away from my pc. Its not a gaming laptop and whenever I start up the cheat it would use 25% of CPU every time on task manager (Windows Command Processor). It removes around 10 fps and makes my craptop run shit. Any reason?

**Comment by phooooon** [comment]
also while you are reading this i have a couple suggestions 

Scroll wheel bhop script
backtrack

**Comment by uniarch** [comment]
bhop sscript already exists
backtrack - https://github.com/TheFuckingRat/RatPoison/issues/95

**Comment by phooooon** [comment]
@uniarch no I mean another one where you use scroll wheel and it makes you hit every time. For mousecam situations

**Comment by mattbot101** [comment]
"stupid rat" is also giving up his damn time and hard work to you for free. Sounds like you shouldn't even bother trying to hide it if people are suspicious enough to ask for a mousecam. And if you were really the legendary phoon, you wouldn't need a cheat ;)

**Comment by TheFuckingRat** [comment]
@mattbot101 You don't need to be aggressive, iirc the scroll wheel bhop was a part of Charlatano but I took it out, I will look into adding it back in.

**Comment by mattbot101** [comment]
He called you stupid rat lmao

**Comment by phooooon** [comment]
@mattbot101 Thats his old account name

**Comment by mattbot101** [comment]
i’m an embarrassment to my entire family
