### ISSUE TITLE
[Question] Stand alone Bhop

### ISSUE THREAD

**Issue by tirziz** [TheFuckingRat/RatPoison#110]
How to build only Bhop on ratposion ? I mean I dont need other features.

**Comment by x7airworker** [comment]
I would suggest that you start from scratch, rather than removing features.

**Comment by tirziz** [comment]
> I would suggest that you start from scratch, rather than removing features.

I just want a decent bhop for SMAC secure servers, and this ratposion more than enough but it drop my fps too much

**Comment by TheFuckingRat** [comment]
Use Charlatano... Jire's version and my fork are both updated and working afaik.
