### ISSUE TITLE
FPS super low on overlay 

### ISSUE THREAD

**Issue by mattbot101** [TheFuckingRat/RatPoison#111]
I reset my PC, so that means I had to reinstall CSGO. I turned all my settings down, even lower than what I had before, but before the overlay ran very smoothly. Now if I move my crosshair back and forth there is a very noticeable and large amount of lag on the boxes and box info with it. What settings can I turn down to make it better? I changed nothing with my hardware.

**Comment by TheFuckingRat** [comment]
No idea what the issue could be but it shouldn't be an issue with the cheat, check the opengl settings to make sure the fps and everything is set right

**Comment by mattbot101** [comment]
Seems like it gradually fixed itself, I changed nothing. Oh well. Works now.
