### ISSUE TITLE
Some minor problems

### ISSUE THREAD

**Issue by furioushell98** [TheFuckingRat/RatPoison#112]
- i used V1.3.4 since its release, it worked fine but in the last few days, the cheat menu keeps disappearing (i press F1, menu shows up for few seconds then it disappears and FPS drops down to 15,  i have to alt tab to see the menu again) i think that a CSGO update caused this. 
- when i spray on someone with rifles or SMGs, the cheat will follow enemy who went back to cover through wall (i'm using default settings btw), it'd be nice to have an option to disable aimlock when target is behind walls.

**Comment by TheFuckingRat** [comment]
I haven't had an issue with the menu disappearing, though the only reason it could (should) happen randomly is if your mouse isn't on csgo or the overlay, or is in the background some other way, which shouldn't be related to csgo but not I can do in terms of fixing it. The aimbot issue is the same as bonetrigger, fake chams and anything needing a visibility check, bspotted is slow and takes a small amount of time (like less than a second) but still takes time to update. This check is disabled when playing danger zone (if the cheat doesnt crash DZ, I haven't tested or been notified in awhile), so danger zone is the only case where aiming through walls is the default

**Comment by furioushell98** [comment]
@TheFuckingRat 
Update 1.4.1 fixed the issue with the constant menu disappearing. Idk how but awesome.
I see what you mean by slow Bspotted. It's not a big deal, i just have to be careful when shooting through smokes or near walls.
One more question, I'm going to play for few days at an internet-café but the PCs have windows7 only. If i disable the overlay and use only aim and radar Ratpoison should work right? And ty
