### ISSUE TITLE
Feature request: sniper crosshair 

### ISSUE THREAD

**Issue by mattbot101** [TheFuckingRat/RatPoison#113]
A crosshair for snipers when they're not scoped would be awesome. For now my sharpie dot on the monitor works good enough, but it’d be cool.

**Comment by BrigDan** [comment]
While I think this might be kinda cool, because the recoil crosshair exists I think it's kinda un-needed. Saves you the sharpie dot too.

**Comment by TheFuckingRat** [comment]
Added as an option separate from recoil crosshair (menu/overlay only)
