### ISSUE TITLE
How to import settings from 1.3.4 to 1.4

### ISSUE THREAD

**Issue by mattbot101** [TheFuckingRat/RatPoison#114]
(sorry about opening so many issues lol) Is there any way to move settings over from 1.3.4 to 1.4? I see in the changelog that settings for different kts's were reworked so I can't just drag and drop the old settings to the new folder (I think). Do I just take screenshots of each setting folder in the menu and put them in individually? Thanks for 1.4 by the way.

**Comment by TheFuckingRat** [comment]
Id recommend just remaking them ingame with the menu, otherwise you'll have to go through each file individually and readd the settings
