### ISSUE TITLE
Featurer Request

### ISSUE THREAD

**Issue by RaiyanAir** [TheFuckingRat/RatPoison#115]
Hitmarker like the one in COD MW2. Also more choices of hitsounds.

**Comment by TheFuckingRat** [comment]
Adding more hitsounds, hitmarker is a maybe

**Comment by mattbot101** [comment]
Can't we change the hitsound audio file if we wanted to? Obviously it wouldn't be an option in the menu, but we could customize it.

**Comment by TheFuckingRat** [comment]
@mattbot101 of course, can edit the files themselves, add new ones, delete old ones
