### ISSUE TITLE
Colors aren't being selected correctly (also a short suggestion)

### ISSUE THREAD

**Issue by spy12085621** [TheFuckingRat/RatPoison#118]
When changing colors on ESP, sometimes it skips details for the colors, when I try to change the color of the box for between cyan and blue (0 RED, 255 BLUE, 125 GREEN), it sees on cyan fully (255 blue and 255 green) and isn't variable for fully customizable colors on visuals.

Also, a short suggestion for Ratpoison to have optional outlines on box, healthbar and text, (enable or disable outilnes on ESP) and to be able to change the color of texts and the skeleton (not only health based) for each team and enemy.

I honestly didn't expect this JAVA cheat to perform without bugs, it's really surprising. whoever is working on this, you are commended.

**Comment by TheFuckingRat** [comment]
Couldn't find any issue with changing the colors, can you provide more details? Was it when moving sliders, typing text into the RGB boxes or anything else you might have done, or is it just randomly not working?

**Comment by spy12085621** [comment]
> Couldn't find any issue with changing the colors, can you provide more details? Was it when moving sliders, typing text into the RGB boxes or anything else you might have done, or is it just randomly not working?

No, sorry I didn't detail it better.
Ok, so I go into the Visuals > Box tab, I try to choose the color for the box of the entities, when I try to change, in particular, a color between blue and cyan, when applying 255 to the blue and just 25 or 50 to green (on RGB context), it snaps to full cyan, as if it identified 255 green, same when I put 1 to green, it still has the full cyan color, and then when I lower it down to zero, the color snaps to normal blue, it's like the color choices are limited by this bug.

**Comment by spy12085621** [comment]
The issue still doesn't seem to be resolved on the version 1.4.1, setting the blue level on 255 and increasing just one from green will set the box color to full cyan, as if it was level 255 of green.

**Comment by TheFuckingRat** [comment]
@spy12085621 Sorry for the very late reply, but I just now found the issue with the box colors not working appropriately (and also setting box esp/skeleton esp/other colors incorrectly), will be solved in the next update.

**Comment by spy12085621** [comment]
> @spy12085621 Sorry for the very late reply, but I just now found the issue with the box colors not working appropriately (and also setting box esp/skeleton esp/other colors incorrectly), will be solved in the next update.

Cool, thanks for your attention. Also, yeah, I am also busy most of the times with some stuff.
