### ISSUE TITLE
What is the normal average CPU usage

### ISSUE THREAD

**Issue by phooooon** [TheFuckingRat/RatPoison#125]
Title. It has been hogging up to 30 % and it's making the game itself stutter

**Comment by TheFuckingRat** [comment]
Up to 15% when initializing, doesn't peak above 5% after, stays around 2% for me.

**Comment by phooooon** [comment]
@TheFuckingRat hmm that's quite weird. Anything you think I did wrong in installation that would have affected it? 

It's always windows command processor in task manager

**Comment by phooooon** [comment]
@TheFuckingRat also I'm pretty sure you always initialise after you're in the game and can see your gun right

**Comment by TheFuckingRat** [comment]
I'm not sure what the issue could be, but I'd assume an underpowered cpu (I have a 8700k@5ghz), has it always used that much or is it a new issue? Also you can init whenever, I usually init in the main menu and everything works fine, I assume crashes can happen but I haven't had issues.

**Comment by phooooon** [comment]
I've had this issue since 1.3.2 and on. I have an i7 7700hq 4. Something GHz do it should have enough power. Idk why it makes my game stutter like hell

**Comment by phooooon** [comment]
I don't play with any visuals except Radar. Menu always off because I play in full screen mode so I can't access it anyway

**Comment by phooooon** [comment]
Huh must be my device then. I'll wait for the next update. 

Closed
