### ISSUE TITLE
Aim occasionally crashing

### ISSUE THREAD

**Issue by Elektrik1** [TheFuckingRat/RatPoison#126]
Finished loading settings
Launching...
[Debug] Looking for and initializing CSGO
[Debug] CSGO initialized
[Debug] Initializing scripts
[Debug] BHop, AutoStrafe, RCS initialized
[Debug] Recoil Crosshair, FlatAim, PathAim initialized
[Debug] SetAim, BoneTrigger, AutoKnife initialized
[Debug] ReducedFlash, SpectatorList, BombTimer initialized
[Debug] Initializing ESPs
[Debug] GlowEsp, IndicatorEsp, BoxEsp initialized
[Debug] SkeletonEsp, ChamsEsp, HitsoundEsp initialized
[Debug] RadarEsp initialized
[Debug] ESP, ESPToggle, Automatic Weapons initialized
[Debug] FastStop initialized
App Title: Counter-Strike: Global Offensive
[Debug] Updated viewports
Waiting for App
Initializing overlay
[Debug] Updated viewports
Exception in thread "Thread-8" java.lang.NoSuchMethodError: rat.poison.game.EntitiesKt.bones(JI)Lrat/poison/utils/Vector;
        at rat.poison.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt:91)
        at rat.poison.scripts.aim.PathAimKt$pathAim$$inlined$aimScript$1.invoke(Every.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

**Comment by TheFuckingRat** [comment]
Only way I can replicate is a null var when initializing and trying to use aim, wait for the next update (no eta) and see if it's fixed or not

**Comment by Elektrik1** [comment]
Ok. As a hint - it only started to throw this exception since 1.4, ver 1.3.4 works fine with the exact same config.
