### ISSUE TITLE
Problem with Launch

### ISSUE THREAD

**Issue by italycross** [TheFuckingRat/RatPoison#130]
Hello! I have a problem with RatPoison, i start "Start Ratpoison 1.4.1" and the debug says Launching... [Looking for and initializing CSGO] 

Can you help maybe ?

**Comment by italycross** [comment]
I solved it meanwhile, the problem was the resolution in the general and in the game wasn't the same, +1 i had to launch it in administrator mode.

**Comment by TheFuckingRat** [comment]
You shouldn't have to run as administrator but if it works and is a special case I guess its fine.
