### ISSUE TITLE
Hitmarker and Defuse Kit esp do not work

### ISSUE THREAD

**Issue by RaiyanAir** [TheFuckingRat/RatPoison#132]
Does the hitmarker require windowed mode? It didn't work for me. Defuse kit esp does not work. Do I did my teammate glow esp enable for me as CT side to see it.

**Comment by TheFuckingRat** [comment]
The hitmarker and defuse kits can be enabled in the settings files, though they don't actually do anything. They were in progress when I pushed the 1.4.1 fix and the functionality wasn't actually added in.
