### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by justasbeast** [TheFuckingRat/RatPoison#135]
When launching rat poison aim and wallhack works but overlay doesnt work using java 12

**Comment by TheFuckingRat** [comment]
I need more information. Overlay only works when csgo is borderless/windowed, make sure MENU = true in general.kts, and theres no error messages in the cmd, and it says it initializes and everything

**Comment by justasbeast** [comment]
Cs is in fullscreen windowed manu is true in general.kts no errors in cmd and the overlay launnches as separate screeen and stays there

**Comment by TheFuckingRat** [comment]
MENU_APP = "Counter-Strike: Global Offensive" ? I'm assuming you've tried relaunching but if you haven't do it. Is your CSGO named anything other than the above? If it's named the same close it, set MENU_APP to something like "Untitled - Notepad", open a blank notepad and then launch poison and see if the overlay is visible on the notepad

**Comment by justasbeast** [comment]
If i do it on notepad it just says launching..... and nothing happens

**Comment by TheFuckingRat** [comment]
See https://github.com/TheFuckingRat/RatPoison/issues/131 https://github.com/TheFuckingRat/RatPoison/issues/83 for more debugging. Type java -version in cmd and make sure youre using 12

**Comment by justasbeast** [comment]
changed everyhting it still says javaj 1.8 even id deleted it completely

**Comment by justasbeast** [comment]
Deleted java 8 in control panel and it now works
