### ISSUE TITLE
'Java' is not recognized

### ISSUE THREAD

**Issue by noogaimc** [TheFuckingRat/RatPoison#137]
I'm trying to launch Rat Poison but when I do it says, "'java' is not recognized as an internal or external command, operable program or batch file." [https://gyazo.com/55e921ff0624c85abcc5946c90d3bd14](Image) Any way to fix this?

**Comment by TheFuckingRat** [comment]
Jdk 12 isn't installed or your path is incorrect. if typing 'java -version' in a cmd doesn't give you jdk 12 then something is wrong. See https://github.com/TheFuckingRat/RatPoison/issues/136#issuecomment-530856186 for help

**Comment by sukarodo** [comment]
fixed this myself by doing this: 

@echo off
cd /d "%~dp0"
title RatPoison 1.4.1
java -Xmx512m -Xms512m -jar "RatPoison 1.4.1.jar"
pause

in the batch file instead.

**Comment by noogaimc** [comment]
It works now but when I press F1 it opens this https://gyazo.com/53a94f44787b75df18789af5c44e1aca

**Comment by TheFuckingRat** [comment]
If the UI is a separate window you're probably using jdk 1.8 instead of 12.

**Comment by noogaimc** [comment]
But I installed jdk 12 from the link provided by you

**Comment by TheFuckingRat** [comment]
Type 'java -version' in a cmd and see what it says. If you've previously installed 1.8 and then installed 12 and added it to java_home there could still be some issues making it use 1.8 instead, which is most likely the case

**Comment by noogaimc** [comment]
I did and it said it was java 12

**Comment by TheFuckingRat** [comment]
If it says you're using jdk 12, are on windows 10, and csgo is borderless/windowed then theres nothing I can do to help.
