### ISSUE TITLE
crash in deathmatch

### ISSUE THREAD

**Issue by suciuale** [TheFuckingRat/RatPoison#138]
worked flawlessly untill i unchecked scoped only. maybe it was just a coincidence idk but it crashed 

EDIT: happened again in competitive

**Comment by TheFuckingRat** [comment]
What other settings are you using? Chams and snaplines would occasionally cause when I was testing, are you using these? If not ill look into a scoped only issue

**Comment by TheFuckingRat** [comment]
Just pushed a hotfix, let me know if it helps fix some crashing, and if there is anymore crashing/how severe.
