### ISSUE TITLE
Frequently crashing csgo every game

### ISSUE THREAD

**Issue by VoiD199** [TheFuckingRat/RatPoison#139]
Every game my game would crash once. I didn't do anything. It would just randomly crash. Never had this problem on 1.4.1. Help?

**Comment by Jadax** [comment]
Yep, crashes a lot now - though dev did say not tested/there will be bugs so it's to be expected.

**Comment by TheFuckingRat** [comment]
I had issues rarely crashing with chams/snaplines, if you aren't using these post cfg of your settings

**Comment by VoiD199** [comment]
[Legit.txt](https://github.com/TheFuckingRat/RatPoison/files/3613630/Legit.txt)
(uploaded a text file cuz GitHub doesn't support cfgs)
not using any visuals except radar.

**Comment by TheFuckingRat** [comment]
Is the menu disabled for you?

**Comment by VoiD199** [comment]
It isn't. But im starting to notice a pattern here.
It only crashes whenever I try to save or load config in-game.
and it also shows this weird thing that is on an endless loop whenever I crash
![Screenshot (21)](https://user-images.githubusercontent.com/55344042/64920400-ed4b5600-d7e9-11e9-9fb3-c0ce216e00ca.png)

**Comment by TheFuckingRat** [comment]
Just pushed a hotfix, let me know if it helps fix some crashing, and if there is anymore crashing/how severe.

**Comment by VoiD199** [comment]
Thank you. Will do
