### ISSUE TITLE
Why esp & chams is not showing ?

### ISSUE THREAD

**Issue by Asado-san** [TheFuckingRat/RatPoison#140]
i installed it properly 

fixed the configs properly & other things
but the glow,esp & chams aren't showing ?
aimbot & bhop seems to be working fine 

any res recommended when using this? as i am using 4:3 fullscreen

**Comment by TheFuckingRat** [comment]
Res shouldnt matter, the global ENABLE_ESP needs to be true, otherwise it should be working fine...

**Comment by 10urshin** [comment]
> Res shouldnt matter, the global ENABLE_ESP needs to be true, otherwise it should be working fine...

Res doesn't matter but DPI does, If you have your dpi set anything other then 100%, do this : https://www.addictivetips.com/windows-tips/exclude-an-app-from-dpi-scaling-windows-10/
for C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
