### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by italycross** [TheFuckingRat/RatPoison#141]
Hey! 
I tested it for an hour and there is my experiences.
Inv_glow esp is broken for me somehow, it crash the game all the time.
I tried to play with and without overlay, it crashed 1-1 time so I think it doesn't make an impact for crashes. I played with glow ESP without chams and snaplines it randomly crashed anyways. 
Now I try to play without ESP. I will share my experiences,

P.S.: 1.4.1 is safe or not to use until the 1.5 will be fixed?

**Comment by TheFuckingRat** [comment]
Thank you for testing what you could. 1.4.1 should be more stable.

**Comment by TheFuckingRat** [comment]
Just pushed a hotfix, let me know if it helps fix some crashing, and if there is anymore crashing/how severe.

**Comment by italycross** [comment]
Okay, I download the hotfix and I'll write my experiences.
Btw, yesterday I used 1.5 without hotfixes, and I turned on glow ESP after I started the bot, and never crashed.

**Comment by italycross** [comment]
So I tested it for 45 minutes, with my settings stability is good, crash doensn't happened (glowESP only, not champs or snaplines).
I turned on snaplines it crashed instantly. 
I faced with a problem, that overlay doesn't work. I tried in windowed, borderless windowed mode with multiple resolution too but somehow I could't make it work.

**Comment by TheFuckingRat** [comment]
If the overlay is just a black screen/not attaching you're using jdk 1.8 instead of 12. https://github.com/TheFuckingRat/RatPoison/issues/136#issuecomment-530856186

**Comment by italycross** [comment]
In my PC there is only the jdk 12 installed.

**Comment by TheFuckingRat** [comment]
How does the overlay not work?
