### ISSUE TITLE
ESP never shows

### ISSUE THREAD

**Issue by getsmoked777** [TheFuckingRat/RatPoison#145]
I've enabled it in every cfg setting and the "visual hotkey" works to turn the settings on/off in the menu but nothing relating to ESP shows. To see if it was my pc I tried regular Charlantano and the ESP worked right away. Last version also had same ESP issue for me.

All the other features work well.

**Comment by TheFuckingRat** [comment]
Glow/chams atleast should work if Charlatano does as they're basically the same just with more customization, using the menu if everything is checked properly (such as the default settings for glow esp), and it still doesn't work I'm not sure what the issue could be, as it works perfectly fine for me and I'm assuming most other people as well.
