### ISSUE TITLE
Nade Helper issue

### ISSUE THREAD

**Issue by spy12085621** [TheFuckingRat/RatPoison#146]
Only one instance of the nade helper appears in the map from the list, it's not a cfg issue.
Also, the helper dot seems to be misplaced a bit to the left from the crosshair (maybe due to the thickness of the dot or resolution.
Also, the nade helper needs to be split into nade types (smoke, flash, fire, decoy or nade) and movement (stand, run, walk or step)

**Comment by TheFuckingRat** [comment]
Not sure what you mean by 'only one instance appears' but im assuming only one nade spot at a time, I did find an issue with it not showing spots based on your position correctly (will be in next hotfix, might fix the issue you have). I am aware that the dot isn't completely centered atm, and for the nade types/movement I dont have current plans to add that variety innately, so your best bet would be to use the input text for the spot on creation and define the type there.

**Comment by spy12085621** [comment]
> Not sure what you mean by 'only one instance appears' but im assuming only one nade spot at a time, I did find an issue with it not showing spots based on your position correctly (will be in next hotfix, might fix the issue you have). I am aware that the dot isn't completely centered atm, and for the nade types/movement I dont have current plans to add that variety innately, so your best bet would be to use the input text for the spot on creation and define the type there.

Great, thanks for your support. Loving the menu redesign by the way, it's really cool.
