### ISSUE TITLE
Menu not Working

### ISSUE THREAD

**Issue by Infinity-Fire** [TheFuckingRat/RatPoison#147]
my menu isnt working everything else exept probably the indicators and Rcrosshair is working when i press F1 i get a blackscreen or nothing happens sometimes you can see a buggy menu when theres a blackscreen in the leftbottom corner

![2019-09-16_15h13_44](https://user-images.githubusercontent.com/55395937/64962927-9c466b00-d898-11e9-9df2-e4a1a1d57955.png)

![2019-09-16_15h11_54](https://user-images.githubusercontent.com/55395937/64962938-a0728880-d898-11e9-9c10-8423c383c896.png)

ps newest version 1.5 hotfix 2 help

**Comment by TheFuckingRat** [comment]
Id assume youre using jdk 1.8 instead of 12, use 12

**Comment by Infinity-Fire** [comment]
C:\Progra~1\Java\jdk1.8.0_221

**Comment by Infinity-Fire** [comment]
UwU

**Comment by Infinity-Fire** [comment]
and thx for the help hope it gping to work now

**Comment by Infinity-Fire** [comment]
> 
> 
> Id assume youre using jdk 1.8 instead of 12, use 12

now the i dont get a blackscreen but it is still not working it only toggles on and off with f1

**Comment by TheFuckingRat** [comment]
Whats not working? F1 toggles the menu...

**Comment by Infinity-Fire** [comment]
> 
> 
> Whats not working? F1 toggles the menu...

well when i press f1 nothing happen the menu dosnt pop up only the esp shuts on and off plus i have jdk 12 installed now

**Comment by TheFuckingRat** [comment]
type 'java -version' in cmd, is it using 1.8 or 12

**Comment by Infinity-Fire** [comment]
> 
> 
> type 'java -version' in cmd, is it using 1.8 or 12

![2019-09-17_15h16_43](https://user-images.githubusercontent.com/55395937/65044929-27d5ff80-d95e-11e9-8846-6a4d27a3da1e.png)

but it should be jdk 12 i still have jre 1.8

![2019-09-17_15h17_53](https://user-images.githubusercontent.com/55395937/65045020-53f18080-d95e-11e9-88f4-7b0db7ad4d49.png)

**Comment by TheFuckingRat** [comment]
JRE should be jdk 12 as well

**Comment by Infinity-Fire** [comment]
but jre cant be jdk right ? dont you need both

**Comment by Infinity-Fire** [comment]
is the 1.5 hotfix 2 version reday for the new update ?

**Comment by TheFuckingRat** [comment]
Poison doesn't need to be updated every time CSGO updates, unless something major changes it doesn't need to be updated. The JDK included the JRE, any java path should point to the jdk

**Comment by Infinity-Fire** [comment]
![2019-09-17_15h31_24](https://user-images.githubusercontent.com/55395937/65046072-34f3ee00-d960-11e9-80bf-715775508198.png)

like that ?

**Comment by Infinity-Fire** [comment]
![2019-09-16_15h11_54](https://user-images.githubusercontent.com/55395937/65046105-40471980-d960-11e9-8cdd-9863777579fb.png)
![2019-09-16_15h13_44](https://user-images.githubusercontent.com/55395937/65046109-4210dd00-d960-11e9-8f5c-5fc6a31bd717.png)
![2019-09-17_15h30_18](https://user-images.githubusercontent.com/55395937/65046114-43420a00-d960-11e9-930b-99f8d24af93a.png)

**Comment by TheFuckingRat** [comment]
Can't tell if you're on windows 7 or 10, but the overlay is only supported on windows 10. If 'java -version' says its using 12 then it should be working fine, if not you'll have to google around or look for any oracle/*** in your environment path variables that would redirect java_home

**Comment by Infinity-Fire** [comment]
yeah i have windows 10

**Comment by Infinity-Fire** [comment]
![2019-09-17_15h56_47](https://user-images.githubusercontent.com/55395937/65048269-1e4f9600-d964-11e9-95ef-a0cb2c269602.png)
![2019-09-17_15h57_42](https://user-images.githubusercontent.com/55395937/65048271-1f80c300-d964-11e9-85ec-b2daeddaee48.png)
![2019-09-17_15h56_37](https://user-images.githubusercontent.com/55395937/65048274-20b1f000-d964-11e9-8288-b3bb015625ab.png)

**Comment by Infinity-Fire** [comment]
i cant get it to say 12

**Comment by TheFuckingRat** [comment]
Check for program files\Oracle\*** and delete anything similar, also check C:\Windows\System32\java.exe , 'where java' in cmd to the location, refer to https://stackoverflow.com/questions/14119983/java-home-and-path-are-set-but-java-version-still-shows-the-old-one/50766853 and https://superuser.com/questions/237737/why-is-java-version-returning-a-different-version-to-the-one-defined-in-java-ho for any extra help

**Comment by Infinity-Fire** [comment]
i think there is no way to get java 12 shown there when you search java -version its always 1.8

can you send me a picture of yours ?

**Comment by TheFuckingRat** [comment]
![Capture](https://user-images.githubusercontent.com/46275653/65059980-a0c45f80-d93c-11e9-8276-739fd3145b0c.PNG) Everyone else that uses the cheat has done the same things

**Comment by Infinity-Fire** [comment]
![2019-09-17_18h20_27](https://user-images.githubusercontent.com/55395937/65060351-fb2ee180-d977-11e9-915c-613a88e79fb8.png)

jay now i only needs to work

**Comment by Infinity-Fire** [comment]
works now thx

**Comment by Infinity-Fire** [comment]
> 
> 
> ![Capture](https://user-images.githubusercontent.com/46275653/65059980-a0c45f80-d93c-11e9-8276-739fd3145b0c.PNG) Everyone else that uses the cheat has done the same things

so yeah it works now but in the newes version you always have yourselve or your teammates glowing you cant turn it off when you have cams on thats kinda anoing and you cant turn it off either pls pix Thanks

**Comment by TheFuckingRat** [comment]
If you mean the chams brightness causing yourself/teammates to 'glow' then theres nothing that can be done about it, it tries to balance it as much as possible to seem normal based on the selected brightness, but if the entities are white/whiteish turn down shadow/shader (I forget the name, cant check atm) quality in settings.

**Comment by Infinity-Fire** [comment]
> 
> 
> If you mean the chams brightness causing yourself/teammates to 'glow' then theres nothing that can be done about it, it tries to balance it as much as possible to seem normal based on the selected brightness, but if the entities are white/whiteish turn down shadow/shader (I forget the name, cant check atm) quality in settings.

![2019-09-18_17h14_55](https://user-images.githubusercontent.com/55395937/65161443-e1ed6a00-da37-11e9-92c9-f68cea9a041e.png)

thats the best i yould do not so good in my view
![2019-09-18_17h15_56](https://user-images.githubusercontent.com/55395937/65161506-f9c4ee00-da37-11e9-9319-008306c4e28f.png)

**Comment by TheFuckingRat** [comment]
![Chams1](https://user-images.githubusercontent.com/46275653/65322182-b4094200-db6b-11e9-9626-667aac6e7e0f.png)
![Chams2](https://user-images.githubusercontent.com/46275653/65322186-b7043280-db6b-11e9-8b54-861d5b5e7962.png)
![Chams3](https://user-images.githubusercontent.com/46275653/65322192-b8cdf600-db6b-11e9-871b-e1c9269853a0.png)

Seems to be working fine for me, in the screenshots you sent brightness being 0 nothing should be glowing like that, so my guess is they are two different instances, or you didn't toggle the menu for it to apply

**Comment by Infinity-Fire** [comment]
> 
> 
> ![Chams1](https://user-images.githubusercontent.com/46275653/65322182-b4094200-db6b-11e9-9626-667aac6e7e0f.png)
> ![Chams2](https://user-images.githubusercontent.com/46275653/65322186-b7043280-db6b-11e9-8b54-861d5b5e7962.png)
> ![Chams3](https://user-images.githubusercontent.com/46275653/65322192-b8cdf600-db6b-11e9-871b-e1c9269853a0.png)
> 
> Seems to be working fine for me, in the screenshots the brightness is set to 0 so nothing should be glowing like it is, so my guess is they are two different instances, or you didn't toggle the menu for it to apply, or it's not updating how it should, which it seems like it does correctly from my testing.

hmm well i have another question how can i change my menu to black or another color its kinda hard to see thx

**Comment by matt1tk** [comment]
It’s in misc, menu transparency i think

**Comment by Infinity-Fire** [comment]
> 
> 
> It’s in misc, menu transparency i think

nope XD

**Comment by TheFuckingRat** [comment]
Currently you can't change the color of the menu elements (easily/using the menu), however the general color groups can be changed here https://github.com/TheFuckingRat/RatPoison/blob/master/skin/tinted.json#L6 changing the t-white through t-alpha elements will update the colors on restart.

**Comment by Infinity-Fire** [comment]
> 
> 
> Currently you can't change the color of the menu elements (easily/using the menu), however the general color groups can be changed here https://github.com/TheFuckingRat/RatPoison/blob/master/skin/tinted.json#L6 changing t-white through t-alpha will update the colors on restart.

could you send me your config ?

**Comment by TheFuckingRat** [comment]
If you mean the colors, I just use the default. If you mean what I use ingame it's usually close to the default settings
