### ISSUE TITLE
pressing Q key kills my fps

### ISSUE THREAD

**Issue by suciuale** [TheFuckingRat/RatPoison#150]
idk why but pressing Q key kills my fps, occasionally freezes my game or crashes it.
EDIT: it isn't happening all the time and i don't know what triggers it

**Comment by TheFuckingRat** [comment]
HEAD_WALK_KEY is Q by default, but that's currently disabled and shouldn't be doing anything. Just change the key to something you wouldn't press for now.

**Comment by suciuale** [comment]
found out it wasn't about the Q key. the game just randomly becomes unplayable when a player is in my fov.

this is my config:

[Legit.zip](https://github.com/TheFuckingRat/RatPoison/files/3627370/Legit.zip)

**Comment by TheFuckingRat** [comment]
I'm not having any issues and everything seems fine, will look into any potential problems when I can

**Comment by suciuale** [comment]
Found out that the lag is only when using pistols. see video: https://youtu.be/ngoUYTyrGZM

**Comment by TheFuckingRat** [comment]
Thanks for the extra info and providing a video, hotfix 6 might fix this issue, let me know if it does or not. Have you tried different pistol settings to see if certain things cause the issue? I was not able to replicate the fps dips
