### ISSUE TITLE
When automatic weapons is on, it shoots while clicking in buy menu. 

### ISSUE THREAD

**Issue by matt1tk** [TheFuckingRat/RatPoison#152]
Basically title, when automatic weapons is turned on, any time you click in the buy menu, it shoots. 1.5 is absolutely amazing btw.

**Comment by TheFuckingRat** [comment]
Shouldn't happen nearly as often with 1.5 hotfix 4.

**Comment by matt1tk** [comment]
Oh fuck yeah, another version. thanks.
