### ISSUE TITLE
Skeleton and Box ESP not updating

### ISSUE THREAD

**Issue by Smurf12** [TheFuckingRat/RatPoison#153]
Hi I'm quite new to using RatPoison.
When I turn on the Skeleton and Box ESP, it doesn't correctly display where enemies are.
By this I mean that when I move around the ESP all stays at their original position and doesn't update to match where the targets are.
Not sure if I need to set my FPS setting to my monitor's refresh rate, but that's what I did and nothing really changed.
I'm using latest version and running borderless fullscreen as well.
Thanks in advance

**Comment by TheFuckingRat** [comment]
Try using the default settings and enabling skeleton/box esp and see if it works because it is for me.
