### ISSUE TITLE
"Issued too many commands to server" kick

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#154]
I'm using a bind/aliases to spam radio commands. I can play fine with it, but as soon as I jump using mouse wheel with 'Fast Stop' turned on, I get kicked for the reason stated in the title. Not sure if something can be done about it, but I wanted to bring it to your attention. You can paste this in your cfg if you want to test it out (switches on/off using j):

// TOGGLE RADIO COMMAND SPAM
bind "j" toggle_radiospam
alias radiocmd "getout"
bind "w" +f1
bind "s" +b1
bind "a" +ml1
bind "d" +mr1
bind "MWHEELUP" +jump
bind "MWHEELDOWN" +jump
alias +f1 "+forward"
alias -f1 "-forward"
alias +b1 "+back"
alias -b1 "-back"
alias +ml1 "+moveleft"
alias -ml1 "-moveleft"
alias +mr1 "+moveright"
alias -mr1 "-moveright"
alias +f2 "+forward;getout"
alias -f2 "-forward;getout"
alias +b2 "+back;getout"
alias -b2 "-back;getout"
alias +ml2 "+moveleft;getout"
alias -ml2 "-moveleft;getout"
alias +mr2 "+moveright;getout"
alias -mr2 "-moveright;getout"
alias toggle_radiospam toggle_rs_on
alias toggle_rs_on "alias toggle_radiospam toggle_rs_off;alias +f1 +f2;alias -f1 -f2;alias +b1 +b2;alias -b1 -b2;alias +ml1 +ml2;alias -ml1 -ml2;alias +mr1 +mr2;alias -mr1 -mr2;"
alias toggle_rs_off "alias toggle_radiospam toggle_rs_on;alias +f1 +forward;alias -f1 -forward;alias +b1 +back;alias -b1 -back;alias +ml1 +moveleft;alias -ml1 -moveleft;alias +mr1 +moveright;alias -mr1 -moveright;"

**Comment by TheFuckingRat** [comment]
I believe fast stop is still using dw movement inputs, will look into it and if it is change it to key presses so it shouldn't be an issue anymore. Fix should be in hotfix 7 whenever that gets released.

**Comment by TheFuckingRat** [comment]
So I checked and fast stop does use key presses so it shouldn't really be an issue afaik, but since you're using mouse wheel to jump, it's constantly trying to press the keys make you stop faster (or it should be), so I added a check to slow you down when you're on the ground, so hopefully that will fix the issue, if not reply back, I'll leave this issue open

**Comment by rattedpojzn** [comment]
Thanks for looking into it. Now it kicks me when moving, don't have to jump. But it doesn't really matter, it's low priority. I'll make sure to not use it when I'm spamming.

**Comment by TheFuckingRat** [comment]
Were you using auto strafe?
