### ISSUE TITLE
improvement idea to nades

### ISSUE THREAD

**Issue by 49320190u4321** [TheFuckingRat/RatPoison#155]
is there any way to have profiles automatically loaded depending on which nade you have equipped? i've saved so many nades for each map but tons of them require you to be in the same place for totally different smokes, mollies, and flashes. super confusing and crowded sometimes. 
 if nade types were detected it would make everything a lot better. would also make it so when your gun is out no annoying nade indicators would be in the way.

**Comment by TheFuckingRat** [comment]
Will be added, will require you to either edit the text file and add the nade type (Flash, Smoke, Molly, Frag) after the position name, or recreate each position yourself. The Mirage.txt file will be updated to reflect this change as an example if needed (editing the text file would definitely be faster/easier).

**Comment by 49320190u4321** [comment]
we appreciate the work you do!

**Comment by TheFuckingRat** [comment]
@49320190u4321 If you would like your nade helper files to be added to RP post them here, otherwise I'm assuming this 'issue' is resolved.
