### ISSUE TITLE
GlowESP issue

### ISSUE THREAD

**Issue by italycross** [TheFuckingRat/RatPoison#156]
Hey!

I played yesterday 5 matches and in the last two i had a problem with the glowESP. 
I used model+glow and it worked only with 4 enemy players, but the 5th one stayed "unglowed".
I switched to model only, and i got the same problem, the same player remained "unglowed".

**Comment by TheFuckingRat** [comment]
Hotfix 6 might fix the issue, let me know if it does/if you notice some entities don't glow

**Comment by rattedpojzn** [comment]
I noticed that too, affects BoxESP. On one particular instance it showed that the guy was standing somewhere on the map, and going near it update it. Got resolved when the next round started, it was with a previous hotfix tho.

**Comment by TheFuckingRat** [comment]
Assuming resolved
