### ISSUE TITLE
Menu error.

### ISSUE THREAD

**Issue by gosugosusado** [TheFuckingRat/RatPoison#159]
The trick works for me, but the menu doesn't open within the game, even opening a bind "f1" since an update.

**Comment by TheFuckingRat** [comment]
I have no idea what you're trying to say

**Comment by gosugosusado** [comment]
> I have no idea what you're trying to say


Hack works here.
However, the menu does not open by pressing the "f1" key.
Sorry for the english, your program is worldwide :)

**Comment by TheFuckingRat** [comment]
Is MENU = true in General.kts? Is CSGO borderless/windowed? Does the overlay show up in your taskbar as a black window?

**Comment by gosugosusado** [comment]
> Is MENU = true in General.kts? Is CSGO borderless/windowed? Does the overlay show up in your taskbar as a black window?


I play in windowed mode.
The menu is active.
Before the upgrade, it was working
CMD opens, hack works, I see the "glow esp"

But the  "f1" menu sometimes opens, sometimes not

Win 10 64 LTSC

**Comment by TheFuckingRat** [comment]
I have no idea why it would work sometimes but not others, if its normal and functioning when it does appear
