### ISSUE TITLE
Cheat gets stuck while launching.

### ISSUE THREAD

**Issue by losscredit** [TheFuckingRat/RatPoison#160]
Literally when I run the bat it gets stuck on : Loading settings...
Settings loaded
Launching...

no matter what i do

**Comment by TheFuckingRat** [comment]
DEBUG = true in general.kts, launch and post what else it says

**Comment by losscredit** [comment]
um seems like it worked once i enabled debug no idea why tho,will make another post if it occurs again thanks :d
