### ISSUE TITLE
ESP doesn't work in danger zone but charm does

### ISSUE THREAD

**Issue by LonelyLinear** [TheFuckingRat/RatPoison#161]
Is it normal?

**Comment by TheFuckingRat** [comment]
![17043b3cbabec2eb28b13efb50e22459](https://user-images.githubusercontent.com/46275653/65535448-0aa5b180-dec7-11e9-8327-7de424e51d2b.jpg)
 Everything is working fine for me, latest version default settings with all visual types enable

**Comment by LonelyLinear** [comment]
I'm using the latest version,  but when the game starts, the windows at the bottom of left will be closed. And press f1 is no response. (Set for my bad English)

**Comment by TheFuckingRat** [comment]
Overlay requires windows 10, csgo to be borderless/windowed, and using jdk 12. Is the overlay visible in the taskbar? Does anything related to the overlay show up?

**Comment by LonelyLinear** [comment]
Win10 and borderless, and using jdk12, yes. The overlay is visible in the taskbar before start the game. when the game start, it closed, I open it again, sometimes it's normal, I can use it until the game over, but most of the time, the cheat will close again at a moment.
