### ISSUE TITLE
Can't disable Aim strafe 

### ISSUE THREAD

**Issue by matt1tk** [TheFuckingRat/RatPoison#162]
For some reason aim strafe is on and I can't turn it off.

**Comment by TheFuckingRat** [comment]
It isn't enabled with default settings, and checking/unchecking it works fine from what a quick test. Give a cfg if it's not an issue with default.

**Comment by matt1tk** [comment]
Could it be because I have experimental on?

**Comment by matt1tk** [comment]
Edit: seems like it's not happening any more, but it def was. Oh well, ill reopen if it becomes an issue.
