### ISSUE TITLE
Random characters spammed when auto strafe is on and you try to type in chat

### ISSUE THREAD

**Issue by matt1tk** [TheFuckingRat/RatPoison#163]
It's a great way to express surprise when it says "AAAADDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAADDDDDDDDDDDDDD" but I think it's a bug...

**Comment by TheFuckingRat** [comment]
Forgot to add checks, will be in the next hotfix in a couple minutes

**Comment by matt1tk** [comment]
Thanks.

**Comment by matt1tk** [comment]
@TheFuckingRat Still happens and now for some reason it stops me while I'm moving constantly. Still types in chat but like "wawa" and not spamming.

**Comment by TheFuckingRat** [comment]
Is this only with auto strafe on? The only time it should be pressing W is with fast stop or headwalk (experimental which you have enabled). I need as much information as possible, I don't have a ton of time to test/debug

**Comment by matt1tk** [comment]
Think it was headwalk, i had it enabled. I wasn’t over anyone but that was the issue. I shouldn’t have had it on though since i wasn’t above anyone.

**Comment by TheFuckingRat** [comment]
I haven't touched it since it was added originally so I'm not surprised It's buggy

**Comment by matt1tk** [comment]
It actually works fine if you’re on someone, it just seems to jitter when
you’re not, which is hardly a mistake because it’s not meant to be on when
walking around.

**Comment by TheFuckingRat** [comment]
Made some changes to it so it should be better. Will be in the next update
