### ISSUE TITLE
Autostrafe still works even when disabled and then spawns alphabets such as "A" and "D" randomly in the chat

### ISSUE THREAD

**Issue by codyxd** [TheFuckingRat/RatPoison#165]
Title says it all~ Idk but Even if autostrafe is disabled, it still works for me~

**Comment by matt1tk** [comment]
Same error, make sure you are using the latest version.

**Comment by TheFuckingRat** [comment]
@codyxd Autostrafe, aimstrafe or both? @matt1tk Does aimstrafe still have the same issue as before?

**Comment by codyxd** [comment]
@TheFuckingRat I guess its both tbh 
Also, even with both the options turned off, when i my mouse to the left or the right, it strafes that way, making it hard to--aim at the target and whatnot ~
Kindly fix this. Everything else is top notch ~

**Comment by TheFuckingRat** [comment]
@codyxd Does this always happen with default settings because I can't replicate any problems. Post a cfg of the settings you're using if not.

**Comment by matt1tk** [comment]
I’m saying i had the same error on the old version. Seems to be fixed on 1.5.1

**Comment by codyxd** [comment]
yis, i'm using the current build of ratpoison tho @matt1tk 
@TheFuckingRat 
![image](https://user-images.githubusercontent.com/47775604/65699078-29f53800-e09b-11e9-8802-1d1e6a0ca9c6.png)

**Comment by TheFuckingRat** [comment]
I know the hotfix # doesn't show but make sure its hotfix 2, the very latest download
