### ISSUE TITLE
Randomly closing mid game?

### ISSUE THREAD

**Issue by VoiD199** [TheFuckingRat/RatPoison#166]
It randomly closes mid-game. Not crash, but closes. Help?

(also, is there any way to make this work for 4:3? thanks)

**Comment by VoiD199** [comment]
Also, it doesn't happen every time.  Like 1/10 games it will randomly close. It's not a big deal to me but its pretty annoying because sometimes you will have no clue that it closed.

**Comment by TheFuckingRat** [comment]
I need a cfg of your settings, or the whole folder if you don't use the menu. Also does the game, or overlay crash/close? Also if you're asking if the overlay could work with 4:3 fullscreen, no, not with any fullscreen application.

**Comment by matt1tk** [comment]
I get the same thing, it was happening like once every 5 rounds in casual, it seems to be more stable right now. for me I just set my desired config to the default, then keep the folder with the .bat file open, if it crashes just alt tab back in and rerun it. 

Radar hack stays even after crashing
Chams stay after crashing
Anything on the external layer, like box esp, does not stay after a crash

**Comment by metallicpig** [comment]
I'm assuming the overlay crashes, if it doesn't happen with the default settings (from when initially downloaded), or if you don't know if it crashes with the initial default settings, and you don't provide a cfg/your settings then theres nothing I can do. I don't have the time to test every single setting

**Comment by TheFuckingRat** [comment]
If you can't reproduce the issue with the default settings/don't test it, and don't provide a cfg/your settings then there's nothing I can do. I don't have the time to test every single item that uses the overlay.

**Comment by VoiD199** [comment]
Sorry for the late reply, here is my config:
[Legit.txt](https://github.com/TheFuckingRat/RatPoison/files/3661922/Legit.txt)

Note that yesterday I was still using the hotfix 1. Updated to hotfix 2 earlier played 3 matches and in 1 match it closed.

**Comment by VoiD199** [comment]
here's a new issue also. I tried using my old cfg from hotfix 1 on hotfix 2 and this shows:
![Screenshot (22)](https://user-images.githubusercontent.com/55344042/65762024-9da64c00-e152-11e9-90c2-83845c1251c5.png)

**Comment by TheFuckingRat** [comment]
Thank you for providing a cfg. I'm assuming the cfg is pre 1.5.1 but other than the override weapons I don't believe any other settings changed. The error is caused by the GunAimOverride.txt, the cfg has the old values see [here](https://gyazo.com/0d1eab96be314187ba2964e69d70ea8d) vs the [new](https://github.com/TheFuckingRat/RatPoison/blob/master/settings/GunAimOverride.txt#L14) values, so when parsing it creates errors. Just removing the custom weapons from the cfg should work fine (it did for me). I will look into the crashing.

**Comment by VoiD199** [comment]
Alright, thanks :). Closing this for now
