### ISSUE TITLE
Chams and ESP bug

### ISSUE THREAD

**Issue by jwao** [TheFuckingRat/RatPoison#171]
![Screenshot_27](https://user-images.githubusercontent.com/47069336/65824807-2ef5eb00-e245-11e9-9af1-e2b959b4afdd.png)

Self chams disable but still working on the game

![Screenshot_26](https://user-images.githubusercontent.com/47069336/65824820-62387a00-e245-11e9-9d1c-d9e5b463fbd4.png)

ESP bug 

This update brought several bugs, but still thanks for keeping up the good work updating and bringing new features :)

**Comment by TheFuckingRat** [comment]
https://github.com/TheFuckingRat/RatPoison/issues/168 Chams issue is a known bug, for the box/skeleton, there are checks for if the entity is dormant, and the entity list does take time to update. Ive had times where it continues drawing for a couple of seconds and then disappears, as long as it's not staying there 24/7 it shouldnt be a problem.

**Comment by TheFuckingRat** [comment]
Should be fixed in 1.5.2
