### ISSUE TITLE
(SUGGESTION) some suggestions (and issues)

### ISSUE THREAD

**Issue by VoiD199** [TheFuckingRat/RatPoison#172]
**Suggestions:**

Multi - Bone Aimbot (let's say head and chest. It will target both of them depending on how near it is)

RCS % (will only control a certain percent of the recoil. Example I set it to 50% recoil it will only control half of the recoil.)

RCS Depending on the gun-type (Let's say I only want rcs for SMGs and no RCS for rifle)

**Issues:**

Triggerbot sometimes stops working (Even if enabled, sometimes it will not shoot.)

Aimbot will continue to follow the target even through the wall (Let's say someone peeked me and I sprayed him but he fell back. The aimbot will continue to go to him even through the wall making me look sketchy af)

Sometimes rat poison will not work. It's stuck on Launching

Sometimes the overlay stops working when recording with obs (Game capture. When I stop recording overlay will work again. Not sure why but the previous versions I am able to record with obs.)

**Comment by VoiD199** [comment]
[Hotfix 2.txt](https://github.com/TheFuckingRat/RatPoison/files/3666330/Hotfix.2.txt)
Here's my cfg btw.

**Comment by TheFuckingRat** [comment]
Multi bone selection isn't planned, only a specific bone or nearest bone currently. RCS % is already what the RCS smoothing is, .5 is 50%, .2 is 20%, etc. RCS per category and per weapon is planned. 1.5.2 focuses on bringing trigger bot up to the same level as other features, will be out soon. Aimbot following targets has been brought up a lot, the only external visibility check without map parsing is bSpotted, it's slow and takes time to update, it shouldn't follow a target for more than half a second or anything horrendous, nothing I can do about it. If it launches sometimes and not other times I don't really have an idea on the cause, don't run CSGO/Steam/RP as admin, if it always loads with default settings but not with a custom config lmk. Haven't recorded/streamed with the overlay, but its probably an issue with obs anti cheat hook (if thats still a thing), or just obs in general, no idea on that issue either.

**Comment by VoiD199** [comment]
Thanks. The overlay was obs' anti-cheat hook problem. Will be looking forward to 1.5.2 :)
