### ISSUE TITLE
BTrig with force aim

### ISSUE THREAD

**Issue by Ranennder** [TheFuckingRat/RatPoison#173]
When I using btrig with force aim, sometimes it aim to hands and dont shooting. If i change bone from nearest to neck/chest it works fine but neck is too suspiciously because of 70% headshots and if i change to body, sometimes only the enemy’s head is visible, and I cannot kill him. Video with demonstration of problem - https://www.youtube.com/watch?v=U2MfpJWn3hU&feature=youtu.be

**Comment by TheFuckingRat** [comment]
1.5.2 focuses on updating bone trigger, shouldn't be an issue when that update releases.

**Comment by Ranennder** [comment]
ty
