### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by Matsuri233** [TheFuckingRat/RatPoison#174]
Failure: Build failed with an exception.
*what went wrong:
could not determine the dependencies of task :shadowJar
  coud not resolve all files for configuration runtimeClasspath
    could not download vis-ui.jar(com.kotcarb.vis:vis-ui:1.4.4)
      could not get resource https://jcenter.bintray.com/com/kotcrab/vis/vis-ui/1.4.4/vis-ui-1.4.4.jar
         sun.security.validator.ValidatorException:PKIX path building failed .....balabala.....
there are lots of 'could not'....
i have installed latest jdk1.8.0u211&jdk 12.0.2
environment(path) has no problem

**Comment by TheFuckingRat** [comment]
Clean install, and make sure you're using jdk 12 'java --version'

**Comment by Matsuri233** [comment]
I have uninstalled jdk8 and I am using jdk12
java -version   '12.0.2'
but the problem still exists

**Comment by TheFuckingRat** [comment]
Ive added a build to the releases tab, use that instead

**Comment by Matsuri233** [comment]
It woks.Thanks
