### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by embern33** [TheFuckingRat/RatPoison#175]
Whenever I turn on RP my game is locked to 60Hz. I've changed it to 144hz in the OpenGL settings and still have the problem.

Any fixes?

**Comment by TheFuckingRat** [comment]
Made some changes to the overlay in 1.5.2. I've always had issues with the overlay making the game look like its running slower and it should be a little smoother now. I don't recommend setting it higher than 60 fps, 30 fps opengl made it look normally smooth at 165hz, and 60 fps made it look close, but 100+ fps didn't help at all.

**Comment by embern33** [comment]
Alright that fixed it, thanks. (Setting it to 30 FPS in OpenGL instead of 144 :))
