### ISSUE TITLE
Force aim+btrig again

### ISSUE THREAD

**Issue by Ranennder** [TheFuckingRat/RatPoison#178]
Ty for ur response, but now i hav another problem. Force aim aiming through the walls and btrig cant shoot. https://youtu.be/pgaPIvQGgnc

**Comment by TheFuckingRat** [comment]
More of a limitation being external without a map parser. If the enemy is spotted (bSpotted) and you're within the aim FOV, Itll aim at whatever bone is set (nearest in your case), can't do much about it.
