### ISSUE TITLE
(Question) What works better with pistols. Factor recoil on or off?

### ISSUE THREAD

**Issue by VoiD199** [TheFuckingRat/RatPoison#179]
Having a hard time configuring pistols here. When I have factor recoil on it aims either to the ground or to the body when I have aim bone set on the head. But when I have factor recoil off it aims for the head but misses a lot.

**Comment by VoiD199** [comment]
Also, I can't seem to get the nade helper work. It won't toggle on no matter what I do.

**Comment by furioushell98** [comment]
To me factor recoil works fine for all pistols except for deagle ( so i put an override exception for it with disabled factor recoil), for the rest you can enable automatic weapons and just hold aim button and it'll eventually hit, also you can enable RCS and set it to 0.5 you'll hit more shots.
