### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by Obryk123** [TheFuckingRat/RatPoison#180]
When I start the program, a black screen appears in cs, and I can't do anything about it

**Comment by Obryk123** [comment]
oh I changed to full screen mode and there is no black screen anymore but the menu does not work now by clicking F1 minimizes  cs

**Comment by furioushell98** [comment]
The menu shows up in fullscreen windowed/windowed mode, also you need Win10.

**Comment by Obryk123** [comment]
oh so on win7 nothing can be done about it?

**Comment by furioushell98** [comment]
I tried Ratpoison on Win7. You can disable menu in general file and black screen will be gone, and you can use aim on rifles and SMGs, triggerbot on snipers and pistols, and no visuals, but if you want the cheat to work properly (all features and menu) you must get win10

**Comment by Obryk123** [comment]
ok thanks for the reply
