### ISSUE TITLE
Game brightness

### ISSUE THREAD

**Issue by Hayden959** [TheFuckingRat/RatPoison#183]
![lUOKxh3](https://user-images.githubusercontent.com/24902989/66261347-437c3b00-e791-11e9-8b1e-4a66c7332701.png)
when using ratpoison i noticed the game and player models can get really dark, and weapons and deadplayers  will randomly be a very bright white color
![yblLS6q](https://user-images.githubusercontent.com/24902989/66261256-a2d94b80-e78f-11e9-9602-48b4c444ec54.png)

**Comment by TheFuckingRat** [comment]
This is because of chams brightness, it's how the game is, nothing can be done with it, chams hands might not be countering it correctly if not checked though, will look into that part.
