### ISSUE TITLE
crashes frequently

### ISSUE THREAD

**Issue by spamstuffire** [TheFuckingRat/RatPoison#186]
im prob doing something wrong but # # #184 
![he;](https://user-images.githubusercontent.com/56372594/66529935-63826600-ead3-11e9-8822-c124eb9cdef5.PNG)

**Comment by spamstuffire** [comment]
found out im using 1.5.1 is this fixed in 1.5.2

**Comment by spamstuffire** [comment]
nope happened again
![again](https://user-images.githubusercontent.com/56372594/66530354-6a11dd00-ead5-11e9-994f-1db115964fd0.PNG)

**Comment by TheFuckingRat** [comment]
Need a .zip of settings folder/cfg file

**Comment by Zayoe4** [comment]
I'm getting the same issue along with a buffer null error, here is my config file:
`ENABLE_BOMB_TIMER = true
BOMB_TIMER_MENU = true
BOMB_TIMER_BARS = true
BOMB_TIMER_X = 0.0
BOMB_TIMER_Y = 0.0
BOMB_TIMER_ALPHA = 0.75
ENABLE_TRIGGER = false
ENABLE_AUTO_KNIFE = false
PISTOL_TRIGGER = true
RIFLE_TRIGGER = true
SHOTGUN_TRIGGER = true
SMG_TRIGGER = true
SNIPER_TRIGGER = true
PISTOL_TRIGGER_FOV = 20
RIFLE_TRIGGER_FOV = 40
SHOTGUN_TRIGGER_FOV = 20
SMG_TRIGGER_FOV = 50
SNIPER_TRIGGER_FOV = 15
PISTOL_TRIGGER_INCROSS = true
RIFLE_TRIGGER_INCROSS = false
SHOTGUN_TRIGGER_INCROSS = true
SMG_TRIGGER_INCROSS = false
SNIPER_TRIGGER_INCROSS = true
PISTOL_TRIGGER_INFOV = true
RIFLE_TRIGGER_INFOV = true
SHOTGUN_TRIGGER_INFOV = false
SMG_TRIGGER_INFOV = true
SNIPER_TRIGGER_INFOV = false
PISTOL_TRIGGER_AIMBOT = true
RIFLE_TRIGGER_AIMBOT = true
SHOTGUN_TRIGGER_AIMBOT = false
SMG_TRIGGER_AIMBOT = true
SNIPER_TRIGGER_AIMBOT = false
PISTOL_TRIGGER_SHOT_DELAY = 100
RIFLE_TRIGGER_SHOT_DELAY = 100
SHOTGUN_TRIGGER_SHOT_DELAY = 100
SMG_TRIGGER_SHOT_DELAY = 150
SNIPER_TRIGGER_SHOT_DELAY = 100
AIM_ON_TRIGGER = true
TRIGGER_ENABLE_KEY = false
TRIGGER_KEY = 70
ENABLE_BOX_ESP = false
BOX_ESP_DETAILS = false
BOX_ESP_HEALTH = true
BOX_ESP_HEALTH_POS = "L"
BOX_ESP_ARMOR = true
BOX_ESP_ARMOR_POS = "R"
BOX_ESP_NAME = true
BOX_ESP_NAME_POS = "T"
BOX_ESP_WEAPON = true
BOX_ESP_WEAPON_POS = "B"
BOX_SHOW_TEAM = false
BOX_SHOW_ENEMIES = true
BOX_SHOW_DEFUSERS = true
BOX_TEAM_COLOR = Color(red=0, green=0, blue=255, alpha=1.0)
BOX_ENEMY_COLOR = Color(red=255, green=0, blue=0, alpha=0.6)
BOX_DEFUSER_COLOR = Color(red=145, green=0, blue=90, alpha=1.0)
ENABLE_BUNNY_HOP = true
AUTO_STRAFE = false
STRAFE_BHOP_ONLY = true
CHAMS_ESP = true
CHAMS_SHOW_HEALTH = false
CHAMS_BRIGHTNESS = 250
CHAMS_SHOW_TEAM = true
CHAMS_SHOW_ENEMIES = true
CHAMS_SHOW_SELF = true
CHAMS_TEAM_COLOR = Color(red=0, green=0, blue=255, alpha=1.0)
CHAMS_ENEMY_COLOR = Color(red=255, green=0, blue=4, alpha=1.0)
CHAMS_SELF_COLOR = Color(red=255, green=94, blue=0, alpha=1.0)
ENABLE_ESP = true
VISUALS_TOGGLE_KEY = 35
ENABLE_ADRENALINE = false
RADAR_ESP = false
SNAPLINES = false
SNAPLINES_COLOR = Color(red=255, green=255, blue=255, alpha=1.0)
ENABLE_HITSOUND = true
HITSOUND_FILE_NAME = Metal.wav
HITSOUND_VOLUME = 1.0
DEBUG = false
MENU = true
MENU_KEY = 112
MENU_APP = "Counter-Strike: Global Offensive"
OVERLAY_WIDTH = 1920
OVERLAY_HEIGHT = 1080
WARNING = true
AIM_STRAFER = false
AIM_STRAFER_TYPE = 0
AIM_STRAFER_SHIFT = false
AIM_STRAFER_STRICTNESS = 0.15
FAST_STOP = false
HEAD_WALK = true
HEAD_WALK_KEY = 81
ENABLE_AIM = true
AIM_TARGET_SWAP_DELAY = 150
ENABLE_OVERRIDE = false
ACTIVATE_FROM_AIM_KEY = true
TEAMMATES_ARE_ENEMIES = true
FORCE_AIM_KEY = 5
AIM_DURATION = 1
HEAD_BONE = 8
NECK_BONE = 7
CHEST_BONE = 6
STOMACH_BONE = 5
NEAREST_BONE = -1
PERFECT_AIM = true
PERFECT_AIM_CHANCE = 15
PERFECT_AIM_FOV = 10
AIM_BONE = 8
AIM_SPEED = 1
AIM_FOV = 30
AIM_ASSIST_MODE = false
FACTOR_RECOIL = true
ENABLE_FLAT_AIM = false
ENABLE_PATH_AIM = true
ENABLE_SCOPED_ONLY = true
AIM_STRICTNESS = 2.0
GLOW_ESP = true
INV_GLOW_ESP = false
MODEL_ESP = false
MODEL_AND_GLOW = false
GLOW_SHOW_TEAM = false
GLOW_SHOW_ENEMIES = true
GLOW_SHOW_BOMB = true
GLOW_SHOW_BOMB_CARRIER = true
GLOW_SHOW_WEAPONS = true
GLOW_SHOW_GRENADES = false
GLOW_SHOW_TARGET = true
GLOW_TEAM_COLOR = Color(red=0, green=0, blue=255, alpha=1.0)
GLOW_ENEMY_COLOR = Color(red=255, green=0, blue=0, alpha=0.6)
GLOW_BOMB_COLOR = Color(red=255, green=255, blue=0, alpha=1.0)
GLOW_BOMB_CARRIER_COLOR = Color(red=255, green=140, blue=0, alpha=1.0)
GLOW_DEFUSER_COLOR = Color(red=145, green=0, blue=90, alpha=1.0)
GLOW_WEAPON_COLOR = Color(red=251, green=0, blue=255, alpha=0.5)
GLOW_GRENADE_COLOR = Color(red=0, green=255, blue=0, alpha=1.0)
GLOW_HIGHLIGHT_COLOR = Color(red=0, green=174, blue=255, alpha=1.0)
DESERT_EAGLE = oWeapon(tOverride=false, tFRecoil=true, tFlatAim=false, tPathAim=true, tAimBone=8, tAimFov=30, tAimSpeed=1, tAimSmooth=2.5, tAimStrict=2.0, tPerfectAim=true, tPAimFov=10, tPAimChance=15, tScopedOnly=false, tBoneTrig=false, tBTrigBone=0, tBTrigAim=false, tBTrigDelay=0)
DUAL_BERRETA = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
FIVE_SEVEN = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
GLOCK = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
USP_SILENCER = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
CZ75A = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
R8_REVOLVER = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
P2000 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
TEC9 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
P250 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 8, tAimFov = 30, tAimSpeed = 1, tAimSmooth = 2.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 10, tPAimChance = 15, tScopedOnly = false)
MAC10 = oWeapon(tOverride=false, tFRecoil=true, tFlatAim=false, tPathAim=true, tAimBone=6, tAimFov=50, tAimSpeed=1, tAimSmooth=2.0, tAimStrict=2.0, tPerfectAim=true, tPAimFov=15, tPAimChance=10, tScopedOnly=false)
P90 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 2.0, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 15, tPAimChance = 10, tScopedOnly = false)
MP5 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 2.0, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 15, tPAimChance = 10, tScopedOnly = false)
UMP45 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 2.0, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 15, tPAimChance = 10, tScopedOnly = false)
MP7 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 2.0, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 15, tPAimChance = 10, tScopedOnly = false)
MP9 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 2.0, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 15, tPAimChance = 10, tScopedOnly = false)
PP_BIZON = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 2.0, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 15, tPAimChance = 10, tScopedOnly = false)
AK47 = oWeapon(tOverride=false, tFRecoil=true, tFlatAim=false, tPathAim=true, tAimBone=6, tAimFov=60, tAimSpeed=1, tAimSmooth=1.5, tAimStrict=2.0, tPerfectAim=true, tPAimFov=5, tPAimChance=10, tScopedOnly=false, tBoneTrig=false, tBTrigBone=0, tBTrigAim=false, tBTrigDelay=0)
AUG = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
FAMAS = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
SG553 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
GALIL = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
M4A4 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
M4A1_SILENCER = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
NEGEV = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
M249 = oWeapon(tOverride = false, tFRecoil = true, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 60, tAimSpeed = 1, tAimSmooth = 1.5, tAimStrict = 2.0, tPerfectAim = true, tPAimFov = 5, tPAimChance = 10, tScopedOnly = false)
AWP = oWeapon(tOverride=false, tFRecoil=false, tFlatAim=true, tPathAim=false, tAimBone=6, tAimFov=40, tAimSpeed=1, tAimSmooth=1.0, tAimStrict=1.0, tPerfectAim=false, tPAimFov=1, tPAimChance=1, tScopedOnly=true)
G3SG1 = oWeapon(tOverride = false, tFRecoil = false, tFlatAim = true, tPathAim = false, tAimBone = 6, tAimFov = 40, tAimSpeed = 1, tAimSmooth = 1.0, tAimStrict = 1.0, tPerfectAim = false, tPAimFov = 1, tPAimChance = 1, tScopedOnly = true)
SCAR20 = oWeapon(tOverride = false, tFRecoil = false, tFlatAim = true, tPathAim = false, tAimBone = 6, tAimFov = 40, tAimSpeed = 1, tAimSmooth = 1.0, tAimStrict = 1.0, tPerfectAim = false, tPAimFov = 1, tPAimChance = 1, tScopedOnly = true)
SSG08 = oWeapon(tOverride = false, tFRecoil = false, tFlatAim = true, tPathAim = false, tAimBone = 6, tAimFov = 40, tAimSpeed = 1, tAimSmooth = 1.0, tAimStrict = 1.0, tPerfectAim = false, tPAimFov = 1, tPAimChance = 1, tScopedOnly = true)
XM1014 = oWeapon(tOverride = false, tFRecoil = false, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 1.0, tAimStrict = 1.0, tPerfectAim = false, tPAimFov = 1, tPAimChance = 1, tScopedOnly = false)
MAG7 = oWeapon(tOverride = false, tFRecoil = false, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 1.0, tAimStrict = 1.0, tPerfectAim = false, tPAimFov = 1, tPAimChance = 1, tScopedOnly = false)
SAWED_OFF = oWeapon(tOverride = false, tFRecoil = false, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 1.0, tAimStrict = 1.0, tPerfectAim = false, tPAimFov = 1, tPAimChance = 1, tScopedOnly = false)
NOVA = oWeapon(tOverride = false, tFRecoil = false, tFlatAim = false, tPathAim = true, tAimBone = 6, tAimFov = 50, tAimSpeed = 1, tAimSmooth = 1.0, tAimStrict = 1.0, tPerfectAim = false, tPAimFov = 1, tPAimChance = 1, tScopedOnly = false)
ENABLE_HITMARKER = true
HITMARKER_RECOIL_POSITION = false
HITMARKER_COMBO = true
HITMARKER_OUTLINE = true
HITMARKER_SPACING = 5
HITMARKER_LENGTH = 15
HITMARKER_WIDTH = 3F
HITMARKER_COMBO_COLOR = Color(red=255, green=255, blue=255, alpha=1.0)
HITMARKER_COLOR = Color(red=255, green=0, blue=0, alpha=1.0)
HITMARKER_OUTLINE_COLOR = Color(red=0, green=0, blue=0, alpha=1.0)
INDICATOR_ESP = false
INDICATOR_SHOW_ONSCREEN = false
INDICATOR_DISTANCE = 25.0
INDICATOR_OVAL = false
INDICATOR_SHOW_TEAM = false
INDICATOR_SHOW_ENEMIES = true
INDICATOR_SHOW_BOMB = true
INDICATOR_SHOW_DEFUSERS = true
INDICATOR_SHOW_BOMB_CARRIER = true
INDICATOR_SHOW_WEAPONS = true
INDICATOR_SHOW_GRENADES = false
INDICATOR_TEAM_COLOR = Color(red=0, green=0, blue=255, alpha=1.0)
INDICATOR_ENEMY_COLOR = Color(red=255, green=0, blue=0, alpha=0.6)
INDICATOR_BOMB_COLOR = Color(red=255, green=255, blue=0, alpha=1.0)
INDICATOR_BOMB_CARRIER_COLOR = Color(red=255, green=255, blue=0, alpha=1.0)
INDICATOR_DEFUSER_COLOR = Color(red=145, green=0, blue=90, alpha=1.0)
INDICATOR_WEAPON_COLOR = Color(red=251, green=0, blue=255, alpha=0.5)
INDICATOR_GRENADE_COLOR = Color(red=0, green=255, blue=0, alpha=1.0)
AUTOMATIC_WEAPONS = false
AUTO_WEP_DELAY = 10
ENABLE_NADE_HELPER = false
NADE_HELPER_TOGGLE_KEY = 113
NADE_TRACER = true
NADE_TRACER_UPDATE_TIME = 5
NADE_TRACER_TIMEOUT = .5
NADE_TRACER_COLOR = Color(red=4, green=255, blue=0, alpha=1.0)
OPENGL_VSYNC = false
OPENGL_FPS = 60
OPENGL_MSAA_SAMPLES = 0
PISTOL_ENABLE_FLAT_AIM = true
PISTOL_ENABLE_PATH_AIM = false
PISTOL_FACTOR_RECOIL = true
PISTOL_AIM_BONE = 8
PISTOL_AIM_FOV = 30
PISTOL_AIM_SPEED = 0
PISTOL_AIM_SMOOTHNESS = 2.0
PISTOL_AIM_STRICTNESS = 2.0
PISTOL_PERFECT_AIM = true
PISTOL_PERFECT_AIM_FOV = 45
PISTOL_PERFECT_AIM_CHANCE = 100
ENABLE_RECOIL_CROSSHAIR = true
ENABLE_SNIPER_CROSSHAIR = true
RCROSSHAIR_WIDTH = 2
RCROSSHAIR_LENGTH = 33
RCROSSHAIR_ALPHA = 0.5
RCROSSHAIR_XOFFSET = 1
RCROSSHAIR_YOFFSET = -2
RCROSSHAIR_COLOR = Color(red=255, green=255, blue=255, alpha=1.0)
ENABLE_RCS = false
RCS_SMOOTHING_X = 0.7
RCS_SMOOTHING_Y = 0.7
RCS_RETURNAIM = false
ENABLE_REDUCED_FLASH = true
FLASH_MAX_ALPHA = 1
RIFLE_ENABLE_FLAT_AIM = true
RIFLE_ENABLE_PATH_AIM = false
RIFLE_FACTOR_RECOIL = true
RIFLE_AIM_BONE = 6
RIFLE_AIM_FOV = 60
RIFLE_AIM_SPEED = 0
RIFLE_AIM_SMOOTHNESS = 2.5
RIFLE_AIM_STRICTNESS = 2.0
RIFLE_PERFECT_AIM = true
RIFLE_PERFECT_AIM_FOV = 45
RIFLE_PERFECT_AIM_CHANCE = 100
SHOTGUN_ENABLE_FLAT_AIM = false
SHOTGUN_ENABLE_PATH_AIM = true
SHOTGUN_FACTOR_RECOIL = false
SHOTGUN_AIM_BONE = -1
SHOTGUN_AIM_FOV = 50
SHOTGUN_AIM_SPEED = 1
SHOTGUN_AIM_SMOOTHNESS = 1.0
SHOTGUN_AIM_STRICTNESS = 1.0
SHOTGUN_PERFECT_AIM = false
SHOTGUN_PERFECT_AIM_FOV = 1
SHOTGUN_PERFECT_AIM_CHANCE = 1
SKELETON_ESP = false
SKELETON_SHOW_TEAM = false
SKELETON_SHOW_ENEMIES = true
SMG_ENABLE_FLAT_AIM = false
SMG_ENABLE_PATH_AIM = true
SMG_FACTOR_RECOIL = true
SMG_AIM_BONE = 7
SMG_AIM_FOV = 50
SMG_AIM_SPEED = 1
SMG_AIM_SMOOTHNESS = 2.0
SMG_AIM_STRICTNESS = 2.0
SMG_PERFECT_AIM = true
SMG_PERFECT_AIM_FOV = 15
SMG_PERFECT_AIM_CHANCE = 10
SNIPER_ENABLE_FLAT_AIM = true
SNIPER_ENABLE_PATH_AIM = false
SNIPER_ENABLE_SCOPED_ONLY = true
SNIPER_FACTOR_RECOIL = false
SNIPER_AIM_BONE = 6
SNIPER_AIM_FOV = 180
SNIPER_AIM_SPEED = 0
SNIPER_AIM_SMOOTHNESS = 1.0
SNIPER_AIM_STRICTNESS = 1.0
SNIPER_PERFECT_AIM = true
SNIPER_PERFECT_AIM_FOV = 45
SNIPER_PERFECT_AIM_CHANCE = 100
SPECTATOR_LIST = true
SPECTATOR_LIST_X = 0.0
SPECTATOR_LIST_Y = 150.0
SPECTATOR_LIST_ALPHA = 0.75
`

**Comment by TheFuckingRat** [comment]
@Zayoe4 You shouldn't be getting this same error with your cfg, snaplines isn't enabled. Is your issue the game crashing? That should be the only time it prints out buffer null...

**Comment by spamstuffire** [comment]
nope the game stays fine for me atleast

**Comment by spamstuffire** [comment]
[settings.zip](https://github.com/TheFuckingRat/RatPoison/files/3714503/settings.zip)
thats the settings folder

**Comment by spamstuffire** [comment]
it hasn't crashed as much after i ran the gradlew.bat my guess is thats what it was and im just bad at reading. but maybe not

**Comment by spamstuffire** [comment]
[settings.zip](https://github.com/TheFuckingRat/RatPoison/files/3714530/settings.zip)
thats the settings folder inside the build folder

**Comment by Zayoe4** [comment]
I'll make a seperate post when it does crash instead of hi-jacking this one.

**Comment by spamstuffire** [comment]
got vac banned issue closed
