### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by Matsuri233** [TheFuckingRat/RatPoison#193]
![QQ截图20191015075011](https://user-images.githubusercontent.com/55996342/66790210-6c36ca00-ef21-11e9-8398-961144c6527c.png)
![QQ截图20191015075039](https://user-images.githubusercontent.com/55996342/66790212-6e992400-ef21-11e9-8135-23b62d4b9ff1.png)
![QQ截图20191015075201](https://user-images.githubusercontent.com/55996342/66790215-722cab00-ef21-11e9-813d-a00f8eb057a1.png)

**Comment by Zayoe4** [comment]
Jdk 12, not 1.8

**Comment by Matsuri233** [comment]
![12312312](https://user-images.githubusercontent.com/55996342/66802483-285ab980-ef4f-11e9-8170-9f18988ebc4f.png)
same problem

**Comment by Zayoe4** [comment]
Try deleting your jdk and jre and then download them again. Then delete your old copy of the program, then redownload it then try the build again.

**Comment by Matsuri233** [comment]
tried, but useless

**Comment by Matsuri233** [comment]
Is it a gradle problem or net prob?

**Comment by TheFuckingRat** [comment]
Not an issue with RP, don't know what the specific cause is so if you can't figure out the solution from googling it then you're out of luck.
