### ISSUE TITLE
Support for Jdk12 is over

### ISSUE THREAD

**Issue by furioushell98** [TheFuckingRat/RatPoison#194]
https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html
As you can see from the link above, support for jdk 12 is over and people cannot download it in order to run Ratpoison. (just letting you know about this, i got jdk12 already) 
Edit: you can still download it from here though https://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase12-5440181.html

**Comment by NYPDK** [comment]
JDK 13 works as well, no worries.

**Comment by dealvidit** [comment]
This link asks for a sigup, better to use this mirror:

https://www.softpedia.com/dyn-postdownload.php/b15b8528bfd740aa911c7431fee6b944/5dad3c30/14132/0/2

**Comment by furioushell98** [comment]
@dealvidit it doesn't take 3mins to make an oracle account, plus i don't trust other sites over the original release site.

**Comment by siffreinsg** [comment]
https://adoptopenjdk.net/ is as safe as Oracle but doesn't contain any proprietary code (no telemetry, background process running, ...). Everything is open source on GitHub so if you really don't trust them, take a look ;)
RatPoison is working well on OpenJDK/OracleJDK 13 too, and it is up to date ^^
