### ISSUE TITLE
In game menu not working.

### ISSUE THREAD

**Issue by gn03PvP** [TheFuckingRat/RatPoison#195]
I've done everything on the instructions. Downloaded multiple versions, got the archived jdk 12, I've set JAVA_HOME. But I keep having this issue where when I hit f1 to go to the menu, it will either bring me to a black screen, or tab out to this https://cdn.discordapp.com/attachments/634219765531148298/634263910870024193/unknown.png. Nobody else I've talked to has had this issue, but if I could get some help either on here or discord (BruhMoment32#1597) I'd greatly appreciate it.

**Comment by VoiD199** [comment]
What windows version are you using? I think it doesn't work on Windows 7.

**Comment by gn03PvP** [comment]
I was using windows 10 but I figured out the issue. I had JDK 12 installed but I also had regular java installed for another game. For this hack to work you can only have one java installed and it has to be JDK 12. No regular java.
