### ISSUE TITLE
GUI Bugged

### ISSUE THREAD

**Issue by NYPDK** [TheFuckingRat/RatPoison#197]
The GUI shows up as a black screen, I have JDK 12 installed and have the path set up. I would really enjoy using this cheat.

**Comment by TheFuckingRat** [comment]
Search the previous issues for black screen, overlay issue, or similar, it's been discussed multiple times.

**Comment by NYPDK** [comment]
Yes, I actually figured it out just a few moments later but forgot to take down the issue.
