### ISSUE TITLE
Nearest bone (-1) issue in 1.5.2 version

### ISSUE THREAD

**Issue by 44stork44** [TheFuckingRat/RatPoison#198]
Nearest bone (-1) option not working in 1.5.2 version in specific pistolaim,smgaim,rifleaim etc. settings.

**Comment by furioushell98** [comment]
Wdym it does work, try shooting someone with a visible only head and it'll target the head

**Comment by TheFuckingRat** [comment]
https://gyazo.com/3eac0680b368be6a1feb7ea2664a5209 Working fine here, are you checking enable override per specific weapon?

**Comment by 44stork44** [comment]
Yes, this is headbone (8) and stomach bone (5) and these are perfectly working. The nearest bone not working for me but I don't use overlay, I just editing setting files and just specific weapon aim files, I will try with gunaimoverride file too and will see. On the other hand in 1.5.1 version I didn't change anything in gunaimoverride file just in for example rifleaim and changed bone to -1 which is the nearest option and it worked, now with this method not working.
