### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Obryk123** [TheFuckingRat/RatPoison#200]
at my friend's, they got such a mistake
![74682761_708679626351422_6191391461095768064_n](https://user-images.githubusercontent.com/56191641/67165335-02d11400-f384-11e9-9591-a1169d9449a4.png)

**Comment by 10urshin** [comment]
your friend has a crappy graphics driver that doesn't support opengl 3.2.

**Comment by Obryk123** [comment]
Ok thanks for help
