### ISSUE TITLE
GLFW_PLATFORM_ERROR

### ISSUE THREAD

**Issue by dealvidit** [TheFuckingRat/RatPoison#201]
Hi,
My command prompt starts filling up with this error as shown below which eventually causes a black screen:
https://i.imgur.com/q8N387O.png

JDK Version: 12.0.2
Windows: 10 1903
Hardware: Surface Book 2 15" (1060 6GB)

**Comment by 10jasper10** [comment]
#136 
Please try some general steps to fix most issues.

**Comment by dealvidit** [comment]
Well, for now, I find that disabling the menu in the "General.txt" file fixes this issue for me. Without it however, I cannot use the "Box ESP" and stuff like that.

**Comment by Soulhackzlol** [comment]
Hey ! Are you one fullscreen mode ( CSGO ) ?

**Comment by 10jasper10** [comment]
> Hey ! Are you one fullscreen mode ( CSGO ) ?

He shouldn't be if he followed the steps in #136
