### ISSUE TITLE
Menu will not open

### ISSUE THREAD

**Issue by Toxictea2** [TheFuckingRat/RatPoison#202]
Had this error and dont know how to fix it 

![errror](https://user-images.githubusercontent.com/56917258/67382455-7f6a1b00-f55b-11e9-8505-6f5d316ac42a.PNG)

**Comment by TheFuckingRat** [comment]
Might be fixed with the hotfix, disable OPENGL_3 in OpenGL.txt. Reopen/create a new issue if it isn't fixed.
