### ISSUE TITLE
error on jdk

### ISSUE THREAD

**Issue by ashishlee1211** [TheFuckingRat/RatPoison#203]
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_45' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed
Press any key to continue . . .

**Comment by Usernameistakensad** [comment]
can you read it says that it requires Jre 1.8.0_45 just download it and it will work lol.
