### ISSUE TITLE
Bone trigger starts randomly shooting at things that can be broken or wallbanged

### ISSUE THREAD

**Issue by currydude** [TheFuckingRat/RatPoison#205]
Whenever I hover my crosshair over glass or wooden boxes on mirage a site, the bone trigger starts shooting at it for no reason. This issue only happens with snipers and pistols, but not with rifles, smgs or shotguns. I have no idea why this happens, could someone help me with this please?

**Comment by Zayoe4** [comment]
It also goes of when the crosshair passes over enemies guns. Is it possible to make, an option to wallbang enemies as soon as their wallbangable, similar to a rage hack.

**Comment by matt1tk** [comment]
+1, glow also glows on shit like breakable doors lol. My suggestion is use trigger on key and only press it when necessary
