### ISSUE TITLE
RCS is buggy.

### ISSUE THREAD

**Issue by matzyr** [TheFuckingRat/RatPoison#208]
I have both X and Y smoothing values set to 1.0. But when I spray in game RCS doesn't compensate for horizontal recoil at all making the spray look like this (with random spread turned off).
<img width="256" alt="Capture" src="https://user-images.githubusercontent.com/57353237/68118866-b107bc80-ff33-11e9-9887-d99c47b3c380.PNG">

**Comment by 10urshin** [comment]
set it to 2

**Comment by matzyr** [comment]
> set it to 2

2.0??
