### ISSUE TITLE
bone trigger not working

### ISSUE THREAD

**Issue by phooooon** [TheFuckingRat/RatPoison#211]
it only activates aim, doesnt shoot

**Comment by Zayoe4** [comment]
Can you post your config?

**Comment by TheFuckingRat** [comment]
Working fine here...

**Comment by phooooon** [comment]
@Zayoe4 
//Enable bone trigger
ENABLE_TRIGGER = true

//Enable auto knife
ENABLE_AUTO_KNIFE = false

//Enable bone trigger activation when holding the specified weapons
PISTOL_TRIGGER = true
RIFLE_TRIGGER = true
SHOTGUN_TRIGGER = true
SMG_TRIGGER = true
SNIPER_TRIGGER = true

//The bone trigger activation FOV (0 - 90)
PISTOL_TRIGGER_FOV = 20
RIFLE_TRIGGER_FOV = 40
SHOTGUN_TRIGGER_FOV = 20
SMG_TRIGGER_FOV = 50
SNIPER_TRIGGER_FOV = 15

//Activate if incross (recommended for sniper)
PISTOL_TRIGGER_INCROSS = true
RIFLE_TRIGGER_INCROSS = false
SHOTGUN_TRIGGER_INCROSS = true
SMG_TRIGGER_INCROSS = false
SNIPER_TRIGGER_INCROSS = true

//Activate If in FOV
PISTOL_TRIGGER_INFOV = true
RIFLE_TRIGGER_INFOV = true
SHOTGUN_TRIGGER_INFOV = false
SMG_TRIGGER_INFOV = true
SNIPER_TRIGGER_INFOV = false

//Enable aimbot settings when bone trigger activates for these specified weapons
PISTOL_TRIGGER_AIMBOT = true
RIFLE_TRIGGER_AIMBOT = true
SHOTGUN_TRIGGER_AIMBOT = false
SMG_TRIGGER_AIMBOT = true
SNIPER_TRIGGER_AIMBOT = false

//Default initial shot MS delay on bone trigger activation (0 - 1000)
PISTOL_TRIGGER_SHOT_DELAY = 80
RIFLE_TRIGGER_SHOT_DELAY = 80
SHOTGUN_TRIGGER_SHOT_DELAY = 80
SMG_TRIGGER_SHOT_DELAY = 150                  
SNIPER_TRIGGER_SHOT_DELAY = 80

//Enable currently held weapons aimbot setting's on bone trigger activation
AIM_ON_TRIGGER = false

//Enable bone trigger key that enables bone trigger only when TRIGGER_KEY is pressed
TRIGGER_ENABLE_KEY = false

//VK Key Code (http://cherrytree.at/misc/vk.htm), enables bone trigger when held
//Default key is F
TRIGGER_KEY = 6

**Comment by phooooon** [comment]
/close 

Reinstall resolved issue
