### ISSUE TITLE
aimlock

### ISSUE THREAD

**Issue by plan3s** [TheFuckingRat/RatPoison#212]
is there a way to set aimlock to no key so it automatically locks on to the body when the crosshair is on it without needing to hold a key

**Comment by Zayoe4** [comment]
You'd want to try using triggerbot. Trigger will do that AND shoot the gun. It only works with a gun in your hand.

**Comment by plan3s** [comment]
> You'd want to try using triggerbot. Trigger will do that AND shoot the gun. It only works with a gun in your hand.

Is it called BoneTrigger can't find anything else related to Triggerbot, and I don't really want it to shoot the gun because it's kind of obvious/blatant, I just want it to automatically lock on the bone I want without having to hold a key to use Force Aim.
