### ISSUE TITLE
Game hangs while trying to head walk

### ISSUE THREAD

**Issue by Sundolby** [TheFuckingRat/RatPoison#213]
everytime i stand on someones head, the game hangs for like 1 minute and returns back to normal

**Comment by TheFuckingRat** [comment]
It's somewhat intensive in reads/actions per millisecond, will look into optimizing it.

**Comment by matt1tk** [comment]
@Sundolby PC specs? I have a low end ryzen and gtx 750 and I can use it fine.

**Comment by Sundolby** [comment]
> @Sundolby PC specs? I have a low end ryzen and gtx 750 and I can use it fine.

Ryzen 3 2200G
GTX 1070
16GB RAM 2333 Mhz
i mean i can tell u more of my pc if u want but i think these 3 are the important parts

**Comment by matt1tk** [comment]
Make sure you're actually using the gtx 1070 and the hdmi video cable is coming out of the video card and not the mobo lmao. I've seen best buy employees mess that up so you never know

**Comment by Sundolby** [comment]
> Make sure you're actually using the gtx 1070 and the hdmi video cable is coming out of the video card and not the mobo lmao. I've seen best buy employees mess that up so you never know

i built my own pc, i am retarded but not that retarded to actually put it in my own mobo lol
