### ISSUE TITLE
Shader issue

### ISSUE THREAD

**Issue by emulbrasil** [TheFuckingRat/RatPoison#218]
I followed the guide from scratch and was able to create / build ratpoison. However, everytime I try to run it I get the error on the picture (Implicit version number 110 not supported by GL3).

![Untitled](https://user-images.githubusercontent.com/57601461/68550026-a6d73980-03dd-11ea-8c65-1f79dcbead84.png)

Any insights?
ps: I do not code at all, so anyone willing to help, please, treat me as a true begginer :)

Edit: I'm using W7 Professional and my videocard is an ATI 6600M
Edit2: Java JDK version = 13.0.1 (I also tried 12.0.1, but I still got the same error)

**Comment by furioushell98** [comment]
Ratpoison does not work properly on Win7 ( i tested it myself and only aim and triggerbot works, no menu or visuals) Get Win 10.

**Comment by emulbrasil** [comment]
> Ratpoison does not work properly on Win7 ( i tested it myself, win7, jdk 12.0.2, i didn't get these errors and only aim and triggerbot work, no menu or visuals) Get Win 10.

Thanks for your time, but that's not it. From what I've been searching, this has to do with some ATI videocards. I just have no clue on how to fix it (not even where to begin).

**Comment by srTh3uz** [comment]
my windows is 10 and i have the same problem

**Comment by joshuakoo123** [comment]
i have 
windows 10
echo %JAVA_HOME%: jdk-13.0.1
java -version: "1.8.0_231"
AMD Radeon HD 6700 Series - graphics card

same issue please help

**Comment by joshuakoo123** [comment]
Have any of you guys found a solution?

**Comment by joshuakoo123** [comment]
> my windows is 10 and i have the same problem

whats ur graphics card?

**Comment by TheFuckingRat** [comment]
Might be fixed with the hotfix, disable OPENGL_3 in OpenGL.txt. Reopen/create a new issue if it isn't fixed.

**Comment by emulbrasil** [comment]
Did not fix it.
