### ISSUE TITLE
Java not found HELP!!

### ISSUE THREAD

**Issue by WaterMaloneioe** [TheFuckingRat/RatPoison#219]
'java' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

It says that whenever i start up the BAT file

**Comment by plan3s** [comment]
install java

**Comment by furioushell98** [comment]
Install JDK 13 then follow this: https://javatutorial.net/set-java-home-windows-10

**Comment by VoiD199** [comment]
Remove `set path="%JAVA_HOME%";%path%` on the bat file.
