### ISSUE TITLE
my overlay not working

### ISSUE THREAD

**Issue by brwekofc03** [TheFuckingRat/RatPoison#221]
the overlay does not work causing a black screen already done the whole installation again dozens of times suspect that is because I'm using windows 7

**Comment by brwekofc03** [comment]
![image](https://user-images.githubusercontent.com/56983902/68950183-65a6a700-079a-11ea-8853-c3fc08f47ccf.png)

this is my csgo screen

**Comment by furioushell98** [comment]
Ratpoison doesn't work on win7. Get win10.
