### ISSUE TITLE
factor recoil

### ISSUE THREAD

**Issue by plan3s** [TheFuckingRat/RatPoison#222]
Would Vacnet detect if I turn Factor Recoil off?

**Comment by matzyr** [comment]
I've been playing for awhile with Factor Recoil on, no bans. If you don't want to get OW banned turn off ESP.

**Comment by plan3s** [comment]
> I've been playing for awhile with Factor Recoil on, no bans. If you don't want to get OW banned turn off ESP.

Do you know what factor recoil does?

**Comment by matzyr** [comment]
> > I've been playing for awhile with Factor Recoil on, no bans. If you don't want to get OW banned turn off ESP.
> 
> Do you know what factor recoil does?

Basically, makes the aimbot account for weapon recoil while spraying. If its off then shots go all over the place. Always keep it on while aimbotting.
