### ISSUE TITLE
Box ESP causes game to crast

### ISSUE THREAD

**Issue by Zayoe4** [TheFuckingRat/RatPoison#224]
I get a memory exception error and the program crashes. Might be caused by dangerzone update.

**Comment by spy12085621** [comment]
> I get a memory exception error and the program crashes. Might be caused by dangerzone update.

You may be experiencing the same thing as I do, the ESP crashes when it tries to scan for players.

**Comment by TheFuckingRat** [comment]
Box esp caused crashing, should be fixed now. Reopen/create a new issue if not.
