### ISSUE TITLE
opening the .bat bugs the UI

### ISSUE THREAD

**Issue by Soulhackzlol** [TheFuckingRat/RatPoison#225]
Hey! 
When i open the .bat it just show a black UI (Win , 12 sdk Java, windowed) when i launch the java file it works good.
I even try to make an exe (convert bat to exe) and it work well .

**Comment by sendoggo** [comment]
It's written all over the place to use JDK 13. and dont convert .bat to .exe pls....

Havent tested the cheat after the "shattered web" update. prolly broken

**Comment by Soulhackzlol** [comment]
> It's written all over the place to use JDK 13. and dont convert .bat to .exe pls....
> 
> Havent tested the cheat after the "shattered web" update. prolly broken

Ratpoison its better on JDK 12 but it works on JDK 13 , thats not a soluton btw , prob its bec process priority. bec if i dont launch java file the ESP ( now not working btw) is lagged .

**Comment by sendoggo** [comment]
Which Windows version are you using?

**Comment by Soulhackzlol** [comment]
> Which Windows version are you using?

Win 10 oby xD

**Comment by TheFuckingRat** [comment]
I had this issue when the it launched with JDK 1.8 instead of 12/13. This issue comes from this line 'set path="%JAVA_HOME%";%path%' in the build.bat file. Your JAVA_HOME is set incorrectly.
