### ISSUE TITLE
Bhop and Wh isnt working

### ISSUE THREAD

**Issue by Nikutsuke** [TheFuckingRat/RatPoison#228]
Hey guys aimbot works pretty meh cuz its kinda slow bhop doesnt work at all same with WH other things seem to work any ideas?

**Comment by Zayoe4** [comment]
Bhop is pretty inconsistent. And the head walk barely works. I'd recommend updating the head walk more frequently.

**Comment by TheFuckingRat** [comment]
I don't expect normal users to read the actual files, it's more just a reminder for me whenever I look back at it. I didn't intend for headwalk to be usable in it's current state but people asked for it to be enable-able without editing experimental and rebuilding the whole project. 

Bhopping atleast should work fine and be consistent. If you have space bound to jump in-game it's a 50/50 on if it'll actually catch and start bhopping as you hold space. If you unbind space in-game it should work every time.

There shouldn't be an issue with the aimbot, I haven't touched it in awhile. Other than the slow visibility check (can't do anything about it), you can change the speed/smoothing/whatever to how fast or slow you want it.

**Comment by Nikutsuke** [comment]
Bhopping atleast should work fine and be consistent. If you have space bound to jump in-game it's a 50/50 on if it'll actually catch and start bhopping as you hold space. If you unbind space in-game it should work every time 
It doesn't work at all I tried both space bound and unbound enabled bhop in bunnyhop file and in config, via menu "in game" too still nothing ;///

**Comment by Zayoe4** [comment]
It works for me. And I also unbound space and it works perfectly now.
