### ISSUE TITLE
Debug setting invalid 

### ISSUE THREAD

**Issue by Usernameistakensad** [TheFuckingRat/RatPoison#229]
https://gyazo.com/46c3dad0c231030d1bb0db76d457ab92

**Comment by ThatCouldBeMe** [comment]
Give your settings/a cfg or I won't look into it.

**Comment by TheFuckingRat** [comment]
The default settings shouldn't be an issue. 
![Capture](https://user-images.githubusercontent.com/46275653/69850961-38e89a00-1246-11ea-9a6b-26dfc48cb899.PNG) If you're editing settings with the txt files makes sure the lines with actual variables follow the format 'VARIABLE = VALUE', it must contain the spaces, something like 'VARIABLE= VALUE' won't work. Provide a cfg/your settings folder if it happens after saving/loading using the menu.
