### ISSUE TITLE
Ratpoison Black Screen (read all the help.. No use)

### ISSUE THREAD

**Issue by sungardaJ** [TheFuckingRat/RatPoison#232]
Ratpoison immediately makes CS:GO black after I launched it, I am indeed on Windows 10,  and also have set CS:GO to windowed mode, already set JAVA_HOME as variable, tried running the jar file and the bat file but still no work. I am confident it is an overlay-related issue, since I managed to get Charlatano working without overlay-related features (ESP, Chams, Bomb timer, etc). How can it be fixed?

**Comment by TheFuckingRat** [comment]
Does the overlay itself work? CSGO being black is the overlay not being transparent, can you hit F1 and interact with the menu normally?

**Comment by sungardaJ** [comment]
Steam Overlay works fine, menu does appear when I press F1, however everything besides the menu is black

**Comment by TheFuckingRat** [comment]
type 'java -version' in a cmd and make sure you're using jdk 13. 1.8 doesn't make the window transparent. If this isn't the case and you've tried all other troubleshooting from previous github issues then it's a new issue and I dont have the solution.
