### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by printeroutofcyan** [TheFuckingRat/RatPoison#234]
I am on Ratpoison 1.5.3   and the overlay is not transparent. It is also black, I am on windows 10. I have to alt tab to it and it only shows a crosshair and everything else is black

**Comment by M1XT3NZ** [comment]
do you run ratpoison in windowed/fullscreen windowed?
if not then thats the problem most likely

**Comment by printeroutofcyan** [comment]
I am running CS:GO in borderless full screen.
And running ratpoison at same resolution.

**Comment by TheFuckingRat** [comment]
type 'java -version' in a cmd and make sure you're using jdk 13. 1.8 doesn't make the window transparent. If this isn't the case and you've tried all other troubleshooting from previous github issues then it's a new issue and I dont have the solution.

**Comment by printeroutofcyan** [comment]
Thanks I will try this.

**Comment by SIimy** [comment]
> type 'java -version' in a cmd and make sure you're using jdk 13. 1.8 doesn't make the window transparent. If this isn't the case and you've tried all other troubleshooting from previous github issues then it's a new issue and I dont have the solution.

how do i enable jdk 13?
