### ISSUE TITLE
Initializing overlay

### ISSUE THREAD

**Issue by SIimy** [TheFuckingRat/RatPoison#235]
cmd window is stuck at initializing overlay and the "Rat Poison UI" window is just showing on my taskbar and is not able to be pulled up in csgo i believe, im running csgo in windowed

**Comment by TheFuckingRat** [comment]
Try https://github.com/TheFuckingRat/RatPoison/issues/204 https://github.com/TheFuckingRat/RatPoison/issues/130 https://github.com/TheFuckingRat/RatPoison/issues/131 and since I'm assuming the overlay isn't transparent as well https://github.com/TheFuckingRat/RatPoison/issues/234
