### ISSUE TITLE
Error when starting RatPoison

### ISSUE THREAD

**Issue by ArreMinerOnline** [TheFuckingRat/RatPoison#237]
"'java' is not recognized as an internal or external command,
operable program or batch file."

That says when I run the .bat file! Any help would be appreciated!

**Comment by TheFuckingRat** [comment]
![a83da952930af6fb85739b719d539d77](https://user-images.githubusercontent.com/46275653/70847790-38e3bf00-1e2e-11ea-916c-6f4c7f45283f.png)
Already asked and answered several times.
