### ISSUE TITLE
have jdk 13, need jre 13

### ISSUE THREAD

**Issue by SaltyHampster** [TheFuckingRat/RatPoison#238]
my menu doesnt open and shows a blank black page, saw other help threads showing that they had jdk and jre 12/13, only have jdk 13. 

please send download link as I am dumb and probably had it right in front of me this whole time.

**Comment by SaltyHampster** [comment]
![Capture](https://user-images.githubusercontent.com/49771787/70858180-d7684100-1f50-11ea-971e-e1a8e4f83fc8.PNG)

**Comment by TheFuckingRat** [comment]
Its literally in the beginner's guide.
![8eae23141d235bcb4849b14aa87ba61d](https://user-images.githubusercontent.com/46275653/70858576-f96ab080-1ec9-11ea-8efb-70259dbc8b5e.png)

**Comment by SaltyHampster** [comment]
I have jdk 13

**Comment by SaltyHampster** [comment]
I can build, only problem is menu, just black screen, loomed at this help thread (https://github.com/TheFuckingRat/RatPoison/issues/147) but didn't know how he got  
![image](https://user-images.githubusercontent.com/49771787/70858769-76466a80-1f5c-11ea-899e-027f3bc38804.png) to say 12

**Comment by SaltyHampster** [comment]
> Its literally in the beginner's guide.
> ![8eae23141d235bcb4849b14aa87ba61d](https://user-images.githubusercontent.com/46275653/70858576-f96ab080-1ec9-11ea-8efb-70259dbc8b5e.png)

redid that step, didn't fix problem

**Comment by TheFuckingRat** [comment]
"Make sure to update your System Path as well, not just setting JAVA_HOME" Is my guess. Delete 1.8 from your java folder. Remove any path to it in your environment variables, remove anything with Oracle\ in the value. Home and path should point to the jdk. The jdk includes the jre.

**Comment by SaltyHampster** [comment]
> "Make sure to update your System Path as well, not just setting JAVA_HOME" Is my guess. Delete 1.8 from your java folder. Remove any path to it in your environment variables, remove anything with Oracle\ in the value. Home and path should point to the jdk. The jdk includes the jre. Try uninstalling java through control panel (if you used the official install instead of just adding the jdk to your files). Try deletin the %path%= in the notepad file. All of these suggestions have already been said through other issues, if none of them work then there is nothing I can do to help.

works perfect now, thanks
