### ISSUE TITLE
Shader issue / reopening old issue

### ISSUE THREAD

**Issue by emulbrasil** [TheFuckingRat/RatPoison#239]
https://github.com/TheFuckingRat/RatPoison/issues/218

Dear RatPoison, thanks for your time and patience, but your suggestion did not fix it. Any other ideas?

**Comment by TheFuckingRat** [comment]
Can you send your discord#? It'd be easier sending you test builds than releasing possible fixes and hoping for the best

**Comment by thebsniper** [comment]
I am also having the same problem as emulbrasil and have tried the recommendation from post #218 to no avail. I did some looking into this and there appears to be a fix made by some people, but I am definitely not an experienced coder and am unsure of how to implement this fix. I currently run a HIS ice q HD 6970. Any help with this would be greatly appreciated!
