### ISSUE TITLE
Crashes when switching to rifle weapon category under trigger

### ISSUE THREAD

**Issue by mattbot101** [TheFuckingRat/RatPoison#242]
Crashes for me every time :/

Edit: crashes for me any time i switch weapon cat to rifle anywhere as well

**Comment by TheFuckingRat** [comment]
Are you using an outdated version? Working fine for me.

**Comment by mattbot101** [comment]
Yep, just downloaded from the github. Honestly i just edit settings in the
text files lol

**Comment by M1XT3NZ** [comment]
tbh the newest crashes for me all the time too. thats why im using an older one which works flawlessly.
Dont really know why the newest one crashes because i dont get any error message.

**Comment by TheFuckingRat** [comment]
Send your settings

**Comment by mattbot101** [comment]
It seems to be intermittent. It was reproducible while it happened. I
crashed it 6 times, every time when i switched to rifles. But doesn’t
happen now :/

**Comment by TheFuckingRat** [comment]
If it happens again reopen/create a new issue and provide your settings/a cfg.
