### ISSUE TITLE
JAVA_HOME is set to invalid directory

### ISSUE THREAD

**Issue by Lionshide** [TheFuckingRat/RatPoison#243]
![Capture1](https://user-images.githubusercontent.com/31610964/71308673-07708200-2432-11ea-8c81-24e93db81193.PNG)
![Capture2](https://user-images.githubusercontent.com/31610964/71308676-0b9c9f80-2432-11ea-8045-1895df9101c4.PNG)

I don't know what to do right now, I've already done all that you instructed to do and still got an error for no reason (the tutorial)

**Comment by M1XT3NZ** [comment]
You put a ; that’s the error

**Comment by Renato4750** [comment]
Hello, if you're using windows then do the following steps.

Locate your Java installation directory, it'll be something like C:\Program Files\Java\jdk1.13.0.1\

Windows 7 – Right click My Computer and select Properties > Advanced
Windows 8 – Go to Control Panel > System > Advanced System Settings
Windows 10 – Search for Environment Variables then select Edit the system environment variables

Click the Environment Variables button.

Under System Variables, click New.

In the Variable Name field, enter either:
JAVA_HOME

In the Variable Value field, enter your JDK installation path .

**Comment by M1XT3NZ** [comment]
He just ; in his path which isn’t allowed in Paths that’s the error ;)

**Comment by Lionshide** [comment]
ohh thank you very much, already worked
