### ISSUE TITLE
Opening Menu in a different tab.

### ISSUE THREAD

**Issue by meta-Lord** [TheFuckingRat/RatPoison#247]
In the comments to the issue #100 you said that you can open ratpoison menu in a different tab to change or edit a config. Could someone please explain how to open the menu outside the game if you are playing fullscreen.

P.S. I don't care about having to alt tab to change the settings.

**Comment by TheFuckingRat** [comment]
https://gyazo.com/4dc7b516cfdbff7f8cdbb84afd9fa341 Set MENU_APP to the window title of what you want to draw the overlay over, an untitled blank notepad is the easiest, and set the width/height to your monitor's resolution and then fullscreen it.

**Comment by meta-Lord** [comment]
Works well! Thank you so much.
