### ISSUE TITLE
Good rifle aimbot settings?

### ISSUE THREAD

**Issue by meta-Lord** [TheFuckingRat/RatPoison#249]
Does anyone have any good settings for the aimbot that makes the rifle aim not so blatant.

**Comment by TheFuckingRat** [comment]
The default rifle settings aren't blatant, especially if you already know the spray patterns and have decent aim, it will only make minor corrections at that point. If you want it to look less blatant, just set the aim speed UP by one, or set the smoothness + strictness UP by one each.

**Comment by meta-Lord** [comment]
Thank you this helped a lot. The reason it looked blatant it would follow the player jumping very unrealistically. Your suggestion helped a lot.
