### ISSUE TITLE
MicroLags

### ISSUE THREAD

**Issue by PatreskoCZ** [TheFuckingRat/RatPoison#250]
Hey, for start i must tell this is BEST hack what i use. I have a lot of public or private or paid cheats but I LOVE RATPOSION! <3

Now i have small problem. When i start RatPosion(I dont start script but i start JAVA because when i start script
 " 'java' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

But its not my problem, i have problem in game because i see microlags. Boxes,Bomtimer,WatchList blinking and i am a little triger when i must see oit all day. 

So, some help? :D

Thanks

**Comment by TheFuckingRat** [comment]
Follow this https://javatutorial.net/set-java-home-windows-10 to fix java is not recognized blah, you need to set the System Path as well as Java Home, all pointing to jdk 13. Do you mean 'microlags' as the visuals are stuttering/at a low fps?

**Comment by PatreskoCZ** [comment]
The are flashing on and off screen

**Comment by PatreskoCZ** [comment]
BTW. I LOVE YOUR FOR THIS CHEAT MY FRIEND <3

**Comment by PatreskoCZ** [comment]
*UPDATE

MicroLags make my WIDGEt(RainMaster) for PC
