### ISSUE TITLE
[Suggestion] Perfect Defuse

### ISSUE THREAD

**Issue by BachaBajceps** [TheFuckingRat/RatPoison#251]
**I think you can add option to defuse bomb in last _0.01s_. There is already bombState.timeLeftToDefuse, it should be easy, more functions more fun.**

**Comment by matt1tk** [comment]
Hey, so I saw this and worked on it, I'm currently testing it. [Video of it working.](https://streamable.com/xsvpf) There is a caveat. As you can see at timestamp 1:27, I no clipped to the bomb site. However, when I began planting after that time stamp, when the bomb began being planted, that was NOT me holding down my E key. The code works like this: If the time is between 10.2 and 10 (or the equivalent for with a defuser) press the use key to defuse. However. there is no release of the use key. So right after it does the last second bomb defuse, to reset the variable, you will need to press and release your use key, or else it will be "stuck" down. I'm working on a possible fix to this. This shouldn't be a big deal tbh. It doesn't break anything if it gets stuck down. Just remember to do it after and it's fine. Sorry if this is convoluted, TL;DR is that it presses the use key but doesn't release it, so to fix it, some time after the bomb is successfully defused, just press your use key at least once to reset it.
