### ISSUE TITLE
RatPosion- TRIGGER distance

### ISSUE THREAD

**Issue by PatreskoCZ** [TheFuckingRat/RatPoison#253]
Hey my friends <3

Trigger have some distance reaction? 

But when you play Dust2 and stay on T spawn and with AWP look MID DOORS and hold TRIGGER KEY and enemy are visible TRIGGER dont shoot...

Thanks for your time <3

**Comment by TheFuckingRat** [comment]
Are you using Incross, FOV, or both? Incross should work if your crosshair is on him, but FOV uses bSpotted which is too slow to hit that shot.
