### ISSUE TITLE
AutoHolding Aimbot

### ISSUE THREAD

**Issue by PatreskoCZ** [TheFuckingRat/RatPoison#254]
Hello my friend <3

When i fire with AimBot, weapon hold ENEMY.

Can i off only this function?

Thanks

**Comment by PatreskoCZ** [comment]
I dont think auto FOV

**Comment by BachaBajceps** [comment]
Maybe by accident you turn on "Force aim Always",
or you want disable "Activate from fire key"

**Comment by InSovietCS** [comment]
You can do this:

Disable the Activate From Key and disable Force Always.
Then, set the force aim key to a preferred button (i use the upper side mouse button) and use that to aim at your will.
