### ISSUE TITLE
Ratpoison functions aren't working

### ISSUE THREAD

**Issue by Diamond204** [TheFuckingRat/RatPoison#257]
I did reinstall it, I don't know if it was the update or not, but the functions of the cheat aren't working. Altough, the menu and the design part works at all.

**Comment by PatreskoCZ** [comment]
1.Delete all files what you have from RatPosion.
2.Uninstall JAVA from your computer.
3.Download again JAVA from INFO there on GitHub.
4.Instal JAVA and Build RatPosion.
5.COMPLETE

I have a lot of problems and i must solved alone, so its can help you.
