### ISSUE TITLE
Can't start RatPoison

### ISSUE THREAD

**Issue by Kraftium** [TheFuckingRat/RatPoison#259]
Basically, I had 2 Java versions installed: JDK 13 for RatPoison, and JRE 6 for other stuff. My RatPoison was stuck on launching. I decided to delete JRE 6 from Program Files/Java and now it says "Error: could not open `C:\Program Files\Java\jre6\lib\amd64\jvm.cfg'" I suppose RatPoison wants to use JRE 6 for some reason although i set JAVA_HOME and the Path correctly. I then uninstalled JRE 6 and RatPoison works fine. Anything I could do to not have to uninstall the Runtime for RatPoison to work?

**Comment by PatreskoCZ** [comment]
Hey, 
1. Download this (https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
2.Instal 
3. Build RatPosion
4.Play CSGO
5. Go to folder Ratposion build and DONT click on "Start ratposion 1.5.3.3" but only doubleclick on RatPosion 1.5.3.3 (Javaicon)

I dont have set JAVA_HOME and i cant use "Start Ratposion 1.5.3.3"  but when i am in game and only double click on "RatPosion 1.5.3.3" and go to the game and wait 5 second RatPosion work and i enjoy cheating <3

**Comment by Kraftium** [comment]
it works good now, thank you. idk if it was something i did or what you did fixed it but now it works! thanks
