### ISSUE TITLE
FaceIt

### ISSUE THREAD

**Issue by mangalho195** [TheFuckingRat/RatPoison#260]
Not much of an issue, just a question. Any thoughts on trying to find a bypass for the faceit client ac and updating it to be fully functional at all time? Possibly even making a premium version?

**Comment by PatreskoCZ** [comment]
https://github.com/TheFuckingRat/RatPoison/issues/236

<3

**Comment by TheFuckingRat** [comment]
Any even remotely public 'bypass' for the client ac would get patched quick. Only bypassing server side is possible.
