### ISSUE TITLE
Built, but can't run

### ISSUE THREAD

**Issue by zer0S1** [TheFuckingRat/RatPoison#266]
I got this while building(I should mention, while building when it downloads gradle something at the very beggining I lost internet connection for a few seconds but there were no errors)

> Task :compileKotlin
w: C:\Users\User\Desktop\RatPoison\src\main\kotlin\rat\poison\scripts\Ranks.kt: (101, 34): Parameter 'j' is never used, could be renamed to _
w: C:\Users\User\Desktop\RatPoison\src\main\kotlin\rat\poison\scripts\Ranks.kt: (109, 34): Parameter 'j' is never used, could be renamed to _

BUILD SUCCESSFUL in 55s
4 actionable tasks: 4 executed
Press any key to continue . . .

And this when I try running
Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
Waiting for App
Initializing overlay
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : WGL: Failed to make context current: The requested transformation operation is not supported.
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:4492)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3Window.java:442)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:134)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
                rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:124)
                kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
                kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
                kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
                kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : WGL: Failed to make context current: The handle is invalid.
        Stacktrace  :
                org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:4492)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.makeCurrent(Lwjgl3Window.java:442)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:134)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
                rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:124)
                kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
                kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
                kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
                kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by 44stork44** [comment]
Same problem.

**Comment by zer0S1** [comment]
> Same problem.
> 
> EDIT: Update Java JDK and you can use the overlay and everything but this error message repeating yourself in the console.

Putting GO in windowed fullscreen mode worked for me, I mistook the "windowed/fullscreen" part in description as windowed OR fullscreen in which overlay didn't worked, I guess they meant windowed fullscreen.

**Comment by M1XT3NZ** [comment]
It’s windowed or windowed fullscreen ;)
