### ISSUE TITLE
Crashes Often

### ISSUE THREAD

**Issue by InSovietCS** [TheFuckingRat/RatPoison#267]
So the 1.5.4 release is quite unstable... It crashes A LOT... where 1.5.3 would crash maybe once, 1.5.4 is already crashing 4-5 times. 
Built 5 times to ensure validity of result. 
Tested the previous build again, no crashes.

No error message, just freeze and poof goes csgo.

**Comment by Runtg** [comment]
Same

**Comment by PatreskoCZ** [comment]
Same
