### ISSUE TITLE
Menu won't open more than once

### ISSUE THREAD

**Issue by Kuume** [TheFuckingRat/RatPoison#269]
When i open the cheat (i use the .jar file since the .bat file keeps giving me a black screen and the menu isn't opening) and launch csgo the menu works for the first time i open it (with f1)but after that when i close it the menu wont open up a second time and only some of the cheats are working. (usually just the ones that are automatically on). I don't know if this is intentional or if i'm closing the menu wrong or something, but i'd like to know why it isn't really working, thanks.

**Comment by TheFuckingRat** [comment]
Havent heard this issue before, try enabling https://github.com/TheFuckingRat/RatPoison/blob/master/settings/General.txt#L17 menu_stay_focused either in the general.kts settings file or the last tab on the menu.

**Comment by BachaBajceps** [comment]
I think you play cs go on full screen mode, change to window. I had similar problem
