### ISSUE TITLE
setaim faliure - idk what it does

### ISSUE THREAD

**Issue by phooooon** [TheFuckingRat/RatPoison#270]
console gets spammed with setaim failure. its not affecting anything just reporting it

**Comment by TheFuckingRat** [comment]
https://github.com/TheFuckingRat/RatPoison/blob/master/src/main/kotlin/rat/poison/scripts/aim/SetAim.kt#L79 Its what sets the global aim settings for your specific weapon/aim category. If everything is working correctly then yeah no need to worry. Otherwise a restart should fix it.
