### ISSUE TITLE
Keybind doesn't work and overlay doesn't work

### ISSUE THREAD

**Issue by fireflamereed** [TheFuckingRat/RatPoison#275]
When I'm in-game and I hit F1 nothing happens and if I try to tab to the overlay then its black

**Comment by rattedpojzn** [comment]
Are you running CS:GO in windowed or fullscreen windowed?

**Comment by fireflamereed** [comment]
Fullscreen windowed but I tried it in windowed and it’s the same problem

**Comment by BachaBajceps** [comment]
Try to check what's java version you using. In cmd "java -version"

**Comment by fireflamereed** [comment]
![save](https://user-images.githubusercontent.com/60278707/73201470-13bdbe00-4107-11ea-9495-9a74b61e77b7.PNG)

**Comment by fireflamereed** [comment]
should i try in the cmd that starts when i start the hack?

**Comment by TheFuckingRat** [comment]
Use the latest version, it should install it for you now.

**Comment by fireflamereed** [comment]
Thanks this one works
