### ISSUE TITLE
Auto Aim Strafe Explanation

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#278]
Can't find much info on it. I played with it for a couple of minutes and saw how it works, but not sure what it can/would be useful for. Would appreciate an explanation or example. Thanks.

**Comment by TheFuckingRat** [comment]
A friend wanted it added, so I added it. Basically if you have to 180 to aim at someone or flick/whatever it will strafe you a bit as you move your mouse to make it (somewhat?) harder to shoot you.
