### ISSUE TITLE
Triggerbot 

### ISSUE THREAD

**Issue by waterjxze091** [TheFuckingRat/RatPoison#284]
I got this error:
Loading settings...
Settings loaded
Launching...
App Title: Counter-Strike: Global Offensive
PISTOL_TRIGGER_INFOV is empty
- And i can't use triggerbot

**Comment by TheFuckingRat** [comment]
Make sure it's set correctly https://github.com/TheFuckingRat/RatPoison/blob/master/settings/BoneTrigger.txt#L29 if the error isn't because of an error in that file on your end, send a cfg/folder of your settings.
