### ISSUE TITLE
Skeleton giving lags.

### ISSUE THREAD

**Issue by fghghfhgfrty** [TheFuckingRat/RatPoison#289]
i stream using obs, overlay skips frames and retain frames even after turning into another angle.  i have no problem when streaming clean.

**Comment by matt1tk** [comment]
PC specs? Try just using box esp unless you specifically need skeleton ESP

**Comment by fghghfhgfrty** [comment]
> PC specs? Try just using box esp unless you specifically need skeleton ESP

box, stream proof as well? 
gtx1050ti, i3 8th gen, 16gb ram

**Comment by TheFuckingRat** [comment]
Anything that draws/uses the overlay will be stream proof if you're using game capture instead of monitor capture.
