### ISSUE TITLE
JDK v.13 black screen?

### ISSUE THREAD

**Issue by Setse** [TheFuckingRat/RatPoison#290]
I have JDK 13 installed and I still have that black screen issue.
Any idea for fixing the issue? 
Thanks

java version "13.0.1" 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

**Comment by Setse** [comment]
And also is there any way to see the menu while using fullscreen mode?

**Comment by Setse** [comment]
I tried moving up java directory in Path variable, still no luck

**Comment by TheFuckingRat** [comment]
Make sure an older JDK isn't installed/in the Program Files/Java, iirc JDK 8 causes a black screen, and can be being used even if java -version says JDK 13. Try running the .jar itself instead of the run .bat file. If that works then remove this line 'set path="%JAVA_HOME%";%path%' from the .bat file, and re-check your JAVA_HOME.

**Comment by Setse** [comment]
I have only one JDK installed which is jdk-13.0.1. I tried opening the .jar file but it closes itself instantly. Also I double checked that I dont have any file locations with 'Oracle' in them in my environment variables.
![image](https://user-images.githubusercontent.com/17949330/73631920-98a25d80-465a-11ea-92fd-739666f0c50a.png)

**Comment by TheFuckingRat** [comment]
Are you using Windows 7? The overlay only supports W10 at the moment.

**Comment by matt1tk** [comment]
Try using the automatic install script built in to the build.bat.

**Comment by Setse** [comment]
Nah I'm using Windows 10. Automatic JDK install doesn't seem to be working.

**Comment by Setse** [comment]
Tried uninstalling Java and reinstalling, still no luck.

**Comment by matt1tk** [comment]
Hm, strange. Not sure why that wouldn't work. Anyway, click latest release here (https://adoptopenjdk.net/?variant=openjdk13&jvmVariant=hotspot) and run the msi.

**Comment by Setse** [comment]
I've tried adoptopenJDK, still the same issue. Is it maybe with my graphic card with to do?

**Comment by TheFuckingRat** [comment]
Don't know what to tell you, it works with a fresh install of windows without any limitations set in any way. There is an issue with graphics cards being too old to run opengl properly, but that doesn't seem to be the issue here.
