### ISSUE TITLE
doesnt seem to be opening at all, running in background on task manager

### ISSUE THREAD

**Issue by shyringe** [TheFuckingRat/RatPoison#292]
i played with this today, went pretty well and everything worked, after I got off for about an hour I got on again and tried to open ratpoison and it just didn't open, but i see OPENJDK in my task manager

things ive tried:
reinstalling ratpoison
rebuilding after deleting build folder
reinstalling java
restarting pc
making sure java_home is set

yes i have windows 10 64bit

**Comment by matt1tk** [comment]
Does the same occur if you close it with the X button in the menu, as opposed to just closing the command window? I appreciate the report, will look into it.

**Comment by shyringe** [comment]
> Does the same occur if you close it with the X button in the menu, as opposed to just closing the command window? I appreciate the report, will look into it.

yes same thing happens sadly

**Comment by matt1tk** [comment]
Is the issue that you can’t run ratpoison again, or that it runs the JDK in the background? The background issue seems to be an issue with the OpenJDK and not ratpoison. Kill it from the task manager and try again. I’m gonna pick a different JDK because it runs in the background after closing. (not mining obviously)

**Comment by shyringe** [comment]
basically, after i stopped using ratpoison yesterday, when i was done playing cs, i didn't know how to close ratpoison and it just ended up freezing and always staying on top of all other programs, then it stopped responding and windows closed it, later i went to open it again and it doesnt open at all, and just launches a background OpenJDK program, no ratpoison is opened at all, even after reinstalling about everything and restarting my pc and checking java_home

**Comment by matt1tk** [comment]
So can you get it working now? If not, restart your PC, delete the build folder and rebuild (back up your config if you want). Now from now on, to close ratpoison, either use the X in the corner of the actual menu, or alt-tab to the command prompt window and close that.
