### ISSUE TITLE
[Request] (Step ESP)

### ISSUE THREAD

**Issue by BachaBajceps** [TheFuckingRat/RatPoison#295]
It will be great feature to know when can say info to your teammates in legit play.
I'm a little deaf at the footsteps.
I will try to check if that is possible.

**Comment by matt1tk** [comment]
Like sound ESP?

**Comment by BachaBajceps** [comment]
yes, but I think that checking position of sound source will be realy hard, better is check state of enemy. I don't know that is possible

**Comment by TheFuckingRat** [comment]
@BachaBajceps a working version has been added to the beta branch, more customization settings will come soon.

**Comment by BachaBajceps** [comment]
> @BachaBajceps a working version has been added to the beta branch, more customization settings will come soon.

Love you bro!
