### ISSUE TITLE
Minor issue

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#296]
Noticed that while aiming at someone('s head) while you have headwalk turned on, you will move. Only happened with enemies in my case.

Also, is it possible to make smokes semi-transparent? Hopefully one day.

Thanks in advance.

**Comment by TheFuckingRat** [comment]
This isn't happening for me, is it moving you while you're ontop of someones head and aiming at an enemy? Or just when it's enabled at all and you aim at an enemy? Provide a cfg of your settings/a zip of your settings folder.

**Comment by Usernameistakensad** [comment]
happend to me as well when i used to use it it just randomly moved you left, right , forward, back when aimbotting.

**Comment by rattedpojzn** [comment]
Actually, I am using an older version (1.5.3), not sure if .cfg will be useful. By default headwalk is turned off for me, but the couple of times I had it turned on it happened while I was aiming at an enemy (wasn't standing on my teammates). Probably doesn't happen very often, but my friend noticed it too.

**Comment by TheFuckingRat** [comment]
Possibly fixed in 1.6
