### ISSUE TITLE
Nade Helper

### ISSUE THREAD

**Issue by Asviix** [TheFuckingRat/RatPoison#299]
Creating a grenade or Loading a file doesn't work either, any fix? (I did the update)

**Comment by TheFuckingRat** [comment]
Working fine here... make sure its enabled, and the latest version on the menu is 1.5.5.1

**Comment by Asviix** [comment]
That's weird, I use the 1.5.5.1 and enabled it, lemme rebuild it and see if it works

**Comment by Asviix** [comment]
> Working fine here... make sure its enabled, and the latest version on the menu is 1.5.5.1

I found out what was wrong, I need ESP Enabled to have the Grenade Helper Overlay :D
