### ISSUE TITLE
Hey! Not really an issue, just wondering if whenever an update releases is there an easy way to update the cheat without having to rebuild completely?

### ISSUE THREAD

**Issue by roobegissa** [TheFuckingRat/RatPoison#306]
I recently redownloaded the cheat but couldnt get it to build properly. I had to have a friend send me his build. Any way to update without making a new build? Also player FOV would be pretty cool.

**Comment by TheFuckingRat** [comment]
You'll have to redownload and rebuild for each update, in the future it will download the latest version from github at least though. Also what do you mean by player FOV?

**Comment by roobegissa** [comment]
Like the field of view that the player sees.

**Comment by TheFuckingRat** [comment]
Will be added in the next update

**Comment by matt1tk** [comment]
@roobegissa FOV added but is in beta: https://github.com/TheFuckingRat/RatPoison/tree/beta
