### ISSUE TITLE
No idea what happened

### ISSUE THREAD

**Issue by EnviousOne** [TheFuckingRat/RatPoison#307]
Cheat was working just yesterday changed nothing normal day. whenever i load the cheat in and i try to open the menu (f1) it tabs me out and nothing happens. i tried restarting it multiple times but it juist doesnt work . so i tried to go ingame and see, and it shows esp but nothing else and i cant bring up the menu still and it just continues to tab me out.

**Comment by TheFuckingRat** [comment]
Make sure csgo is borderless or windowed, not fullscreen

**Comment by EnviousOne** [comment]
im an idiot, completely forgot about that. idk why my thing changed to fullscreen odd. thank you!
