### ISSUE TITLE
Config Editing Problem

### ISSUE THREAD

**Issue by UnlawfulEagle** [TheFuckingRat/RatPoison#308]
Hey, 
I tried to edit my config and whenever I the PistolAim, RifleAim, SmgAim, SniperAim, or ShotgunAim, I get this in my logs(https://imgur.com/a/WnE6FLZ) and my config won't load
Thanks!

**Comment by TheFuckingRat** [comment]
Provide the broken config, looks like you're setting a variable to an incorrect value.
