### ISSUE TITLE
ESP & Box Issue

### ISSUE THREAD

**Issue by roobegissa** [TheFuckingRat/RatPoison#313]
Hey there! 

So sometimes the glow esp and boxes go invisible and i cant see them for a while (everything else works great), any fixes?

Also, do you plan on adding a FOV circle, which shows ur aimbot fov as a circle around your crosshair.

Thanks!

**Comment by TheFuckingRat** [comment]
If they go invisible there should probably be an error message in the cmd. Box esp has a known crash that will take some time to fix but is in progress, glow has been mentioned before but without an error I can't do anything about. A static FOV option, an FOV circle, and a spread circle are all planned eventually.

**Comment by roobegissa** [comment]
Basically, yes they work. There are certain scenarios where box esp and glow go invisible and then return a few seconds later.

**Comment by TheFuckingRat** [comment]
Box crashing should be fixed in the latest 1.6 update, as long as the glow/box esp return after a few seconds and don't crash then it shouldn't be an issue.
