### ISSUE TITLE
Getting error when loading batch file

### ISSUE THREAD

**Issue by hqvk** [TheFuckingRat/RatPoison#314]
I keep getting this error:

Install JDK (required)? [Y/N] y
Downloading JDK...
Installing JDK...
Building RatPoison...
'Addons\RatPoison-master\' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
Press any key to continue . . .

**Comment by TheFuckingRat** [comment]
See https://github.com/TheFuckingRat/RatPoison/issues/316
