### ISSUE TITLE
JDK doesn't install

### ISSUE THREAD

**Issue by quokka1000** [TheFuckingRat/RatPoison#317]
output:

Install JDK (required)? [Y/N] y
Downloading JDK...
Exception calling "DownloadFile" with "2" argument(s): "De aanvraag is afgebroken: Kan geen beveiligd SSL/TLS-kanaal ma
ken."
At C:\Users\...\Downloads\RatPoison-master\build.ps1:4 char:1
+ $wc.DownloadFile($url, $output)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by matt1tk** [comment]
Seems like HTTPS isn't working for you. Latest commit in beta branch should fix it. (https://github.com/TheFuckingRat/RatPoison/tree/beta) However this seems like a network issue on your end, not sure why https wouldn't work for you. No big deal though, shouldn't make a difference
