### ISSUE TITLE
Name randomizer doesnt work (ik why) 

### ISSUE THREAD

**Issue by gamerboss121** [TheFuckingRat/RatPoison#322]
During the building of the cheat, it prompted if I wanted to randomize the name for safety. After the build was complete I tried to run the cheat and it wouldn't run because RatPoison1.6.jar was missing. Renaming the jar file for the cheat causes it to stop working. changing it back to RatPoison1.6.jar will fix it. When it renames the jar file the bat file needs to change according to the randomized name.

**Comment by matt1tk** [comment]
It works for me. https://github.com/TheFuckingRat/RatPoison/blob/04f0f009e9abb131cd106fcb9751d89bf8d8ce48/ren.bat#L15

**Comment by gamerboss121** [comment]
> It works for me.
> 
> https://github.com/TheFuckingRat/RatPoison/blob/04f0f009e9abb131cd106fcb9751d89bf8d8ce48/ren.bat#L15

Well, I'm not sure what to say then because it didn't for me.

**Comment by matt1tk** [comment]
Paste "Get-Host | Select-Object Version" in your powershell to see what version of powershell you have
