### ISSUE TITLE
Task ;compileKotlin FAILED

### ISSUE THREAD

**Issue by pawloiox** [TheFuckingRat/RatPoison#325]
![image](https://user-images.githubusercontent.com/61801337/75911391-c7754480-5e4f-11ea-9cf0-082fcefc3d74.png)
getting this error, tried manually isntallind jdk

**Comment by JesterWRLD** [comment]
check if your JAVA_HOME is set properly. it should be set to the most recent jdk in program files/java

**Comment by matt1tk** [comment]
Java home isn't set correctly

**Comment by oofnames** [comment]
how do you set java_home

**Comment by matt1tk** [comment]
It gets set automatically if you type "Y" when the build script asks if you want to install the JDK
