### ISSUE TITLE
Can´t build , root project Ratpoison error emssage

### ISSUE THREAD

**Issue by Badjarda** [TheFuckingRat/RatPoison#327]
* What went wrong:
A problem occurred evaluating root project 'RatPoison'.
> org/jetbrains/kotlin/cli/common/PropertiesKt

and often also appears 
gradle not found

![erro1](https://user-images.githubusercontent.com/61871857/76080568-141b6580-5f9f-11ea-8ab2-1400e8311804.PNG)

**Comment by TheFuckingRat** [comment]
There is a prebuilt in the releases tab. It may not be the most updated.

**Comment by JesterWRLD** [comment]
> There is a prebuilt in the releases tab. It may not be the most updated.

i cant seem to find it, it just says one release.

**Comment by matt1tk** [comment]
That's the one
