### ISSUE TITLE
Request: Add a scroll bar in the menu(s)...

### ISSUE THREAD

**Issue by codyxd** [TheFuckingRat/RatPoison#332]
cus--My mousewheel is broken and i can't seem to go down. Kindly Add that, sir. Appreciated.

**Comment by matt1tk** [comment]
Click anywhere in the menu and it will allow you to scroll, can't figure out how to fix it other than that.

**Comment by TheFuckingRat** [comment]
@matt1tk The flick scroll with mouse is disabled by default iirc
@codyxd A scrollbar/mouse drag to scroll will be added/enabled in the next update

**Comment by codyxd** [comment]
thank you so much sir :3
