### ISSUE TITLE
imposssible with dangerzone 

### ISSUE THREAD

**Issue by 1FMan** [TheFuckingRat/RatPoison#335]
big lag spikes, parachute sound glitching, and overall freezes and frame drops when ever launched with danger zone
this doesnt happen in any game mode 
i have tried changing menu fps alot but nothing works 
please fix

**Comment by matt1tk** [comment]
Works fine for me. dz is much harder on any cheat than regular matches, so your PC is probably less powerful.

**Comment by BachaBajceps** [comment]
Dangerzone is really resource hungry because you see all players and weapons on the map. This causes hight RAM usage. I tested that disabling glow is helping. In my case, RAM usage can sometimes exceed 4 GB on cheat. If you have 8GB of RAM, this can be not enough.
