### ISSUE TITLE
Stuck on Launching, doesn't detect csgo

### ISSUE THREAD

**Issue by sam-ui** [TheFuckingRat/RatPoison#347]
After running the bat file it stays stuck on launching, the debug says its "Searching for and initializing CSGO", I ran it as admin, have the process name set correctly and the java home path too. I noticed that no other cheats detect csgo, any suggestions?

**Comment by sam-ui** [comment]
Oh and btw I tested some other cheats and they don't seem to be finding csgo, any clues?

**Comment by sam-ui** [comment]
ok so from what ive seen, I had to restart the pc completely and then if I open csgo it works, after launching and closing EAC though, csgo isnt detected by any cheats until I restart the system

**Comment by Zayoe4** [comment]
Did you get it fixed? Make sure you are running in fullscreen windowed.

**Comment by sam-ui** [comment]
Oh well I didn't exactly fix it but I found the source of the problem, starting Easy eSports makes it so that no cheats are able to detect csgo, even after closing it, until I restart the pc.
