### ISSUE TITLE
Build ps1 not recognised--

### ISSUE THREAD

**Issue by codyxd** [TheFuckingRat/RatPoison#355]
how to fix this error 
It just doesn't seem to work for my friend.
![JPEG_20200406_124655](https://user-images.githubusercontent.com/47775604/78532889-9ba9fd80-7805-11ea-9dea-7671598a79cf.jpg)

**Comment by matt1tk** [comment]
You gotta unzip the whole zip instead of just double-clicking it and running it. else it won't unzip everything, it will just unzip the file you choose.
