### ISSUE TITLE
VAC Kick after uninstalling RatPoison

### ISSUE THREAD

**Issue by Sogli** [TheFuckingRat/RatPoison#359]
I tried RatPoison for 3 days straight on an alternate account that is not linked in any way with my main.  Didn't log in my main at all. Uninstalled it and reinstalled steam so I can be sure that steam can't link me some way with the cheating account. I log into my main and I played 2-3 games and suddenly I get kicked and get an VAC error saying it is being blocked by my computer in some way. I didn't receive this error once while not having RatPoison installed.

**Comment by Sogli** [comment]
I did fuck with the Environment Variables because ratpoison couldn't install adoptjdk by itself, maybe it has something to do with it

**Comment by matt1tk** [comment]
Vac error does not equal ban by the way. And they can happen to legit players. Just try to verify csgo game files
