### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by hackerman339** [TheFuckingRat/RatPoison#361]
Me and my friend are having trouble with the cheat. His cheat opens and runs but never finishes initializing overlay and mine did the same. I tried reinstalling and got this error message Execution failed for task ':RatPoison'.
> java.nio.file.FileAlreadyExistsException: C:\Users\ntrui\Documents\RatPoison-master\RatPoison-master\build\RatPoison 1.6\RatPoison 1.6.jar

**Comment by hackerman339** [comment]
I figured out the problem but another has come. How do i uninstall the jar file for rat poison

**Comment by sam-ui** [comment]
the cheat doesn't install anything so you simply delete the file.
