### ISSUE TITLE
Triggerbot not firing properly if MOUSE1 is not bound directly to +attack

### ISSUE THREAD

**Issue by sotakoira** [TheFuckingRat/RatPoison#362]
My left click key is bound to alias that clears blood and resets grenade crosshair, that is enough to make triggerbot take unusual amount of time to kill the target, roughly between one and ten seconds with shooting delay set to 50.

In https://streamable.com/1r0469 you can see it constantly presses left click while on target.
Binding left click directly to +attack makes triggerbot behave normally again.
Same results on 1.6 and 1.7 beta.

>bind "MOUSE1" "+m1"
>alias +m1 "+attack" 
>alias -m1 "-attack; r_cleardecals; cross_def"

**Comment by matt1tk** [comment]
That's very strange and shouldn't affect it. However a similar issue occurs if you don't unbind +jump and spacebar, bhop sometimes doesn't work. I suspect this is just a general issue with how java cheats work. I'm not sure how this could be fixed.

**Comment by sotakoira** [comment]
seems to be fixed in todays beta
