### ISSUE TITLE
DO I NEED HELP, AND INSURANCE?

### ISSUE THREAD

**Issue by tilenzz** [TheFuckingRat/RatPoison#365]
help me, i use charlatan, this is charlatan but with the menu then ?? he has the same security ?? because I use it and I never took vac and use it in my main account

**Comment by sam-ui** [comment]
don't worry man this is 100% safe it's literally the same source. Of course be careful about using it on your main because if you get overwatched no cheat will help with that. To be honest though this isn't really an issue so pls close it.
