### ISSUE TITLE
Failure to initiate overlay

### ISSUE THREAD

**Issue by Redxjak** [TheFuckingRat/RatPoison#372]
When I run the Start RatPoison 1.6 (And 1.5.5.1) I receive the following:
{
Loading Settings
Settings Loaded
Launching..
_
}

The esp works in game, most of the time. When it finishes starting it minimizes the game and then I have to open the tab again. Then I get into the game and see that the ESP is working, but nothing else, and the overlay is gone(Along with my discord overlay is that matters). Then when I press F1 to open up the menu, the game minimizes and it focuses on the console. It was working perfectly last night, this only started happening today. 

anyone know how to fix this. I tried re-installing this over 5 times but still same.

**Comment by Redxjak** [comment]
I closed the game and this is what my computer is stuck at until I alt tab and close the console manually. 

https://i.gyazo.com/d5a51cc5d001087cab8f492359ee0c56.png

**Comment by matt1tk** [comment]
This is an issue with the menu not correctly attatching to the csgo window. Are you sure you are using Fullscreen Windowed 1080p

**Comment by Redxjak** [comment]
Thank you! I don't know how my settings got changed lol
