### ISSUE TITLE
cant install jdk

### ISSUE THREAD

**Issue by tymurg** [TheFuckingRat/RatPoison#376]
i made one earlier, but i tried again. when i download everything and open the build.bat, and say yes to the jdk it says-
& : The term './build.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:3
+ & './build.ps1'
+   ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./build.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by matt1tk** [comment]
Download and run this msi: http://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.msi

Make sure you enable the home variable. then run the build bat and type "N" to installing the JDK.
