### ISSUE TITLE
Blackscreen / HUD

### ISSUE THREAD

**Issue by GrimekR** [TheFuckingRat/RatPoison#379]
So I tried compiling Rat Poison 1.6 by myself. It worked perfectly. I'm using Windows 10 and I'm playing on fullscreen borderless, as people told me to do. I've got one problem, though. When I boot up Rat Poison via .bat file (I did not change anything in that file, everything worked well) the console shows that everything works, but when overlay launches, it flashes a normal screen with transparent overlay, but suddenly, it turns pitch black and I can't tab out of it, I have to close console via bottom application bar. I don't know how can I solve this problem. I've tried researching, but it doesn't seem to help at all. All I can say is that F1 menu is working and doesn't crash game or anything, but this black screen doesn't really allow me to play normally.

![image](https://user-images.githubusercontent.com/64339001/80294878-d1d7fe80-876d-11ea-91a2-01634fcaaffe.png)

**Comment by matt1tk** [comment]
This is because ratpoison didn't bind to your csgo.exe window. Are you sure you are in 1080p full screen windowed?

**Comment by umesh9248** [comment]
I've had the same issues and I changed the resolution in the settings to fit my screen (1366x768) and even on fullscreen windowed, it doesn't work. I'm on jdk 13 and don't have jdk 1.8 in my system path or variables.

**Comment by GrimekR** [comment]
Yes, my resolution matches my computer screen. I have even got a Full HD 1080p sticker on it so I'm sure and yes, it's full screen windowed, I checked it ingame.

**Comment by rpuser999** [comment]
Type 'java -version' in cmd and if it's not jdk uninstall whatever else java you have and redo the build

**Comment by matt1tk** [comment]
#147 and #136 both address your issue
