### ISSUE TITLE
Chams affect player hands even though Self-Chams are turned off

### ISSUE THREAD

**Issue by GitZurah** [TheFuckingRat/RatPoison#383]
Basically title.
Whenver I use enemy chams with a brightness of over 0, my hands start to get brighter aswell which looks rather irritating, especially if you don't want handchams.

**Comment by TheFuckingRat** [comment]
The brightness is a global modifier, so the alpha of the hands are changed to try to rectify this as best as possible, but it only helps so much. If your hands are turning white turn shader detail to low in game settings.
