### ISSUE TITLE
1.7 beta overlay Didnt show up

### ISSUE THREAD

**Issue by RamyS2K** [TheFuckingRat/RatPoison#386]
I tried the 1.7 Beta, but the overlay didn't show up, i left my laptop running for 5-10 minutes and nothing happened. Help?

Thanks.

Well, just to let you know that i use 1.6 version before, it worked perfectly

**Comment by GitZurah** [comment]
same problem here, also using Win10 as suggested. 1.6 Overlay worked fine but I wanted to try out 1.7 because my Glow ESP kept disappearing and I had some problems with the skin changer

**Comment by RamyS2K** [comment]
> same problem here, also using Win10 as suggested. 1.6 Overlay worked fine but I wanted to try out 1.7 because my Glow ESP kept disappearing and I had some problems with the skin changer

I asked discord members about what happened. you need to change from false to true in gui/overlay settings on General.txt
