### ISSUE TITLE
Issues with build.bat

### ISSUE THREAD

**Issue by kugelnova** [TheFuckingRat/RatPoison#387]
![image](https://user-images.githubusercontent.com/64538169/80980886-8b208d80-8e6c-11ea-85b9-58f2a69c029b.png)

**Comment by kugelnova** [comment]
Also I've tried downloading JDK manually from http://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.msi but it still didn't work.

**Comment by matt1tk** [comment]
Download it manually and install it, then type N when it asks whether you need it.
