### ISSUE TITLE
'gradlew' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kugelnova** [TheFuckingRat/RatPoison#391]
I have downloaded JDK manually.

![image](https://user-images.githubusercontent.com/64538169/81241324-443dbe00-904d-11ea-9c94-0745dd9c1816.png)

**Comment by matt1tk** [comment]
The path was not set. https://docs.oracle.com/cd/E19182-01/821-0917/inst_jdk_javahome_t/index.html
