### ISSUE TITLE
Error when building 1.6

### ISSUE THREAD

**Issue by yangluke199** [TheFuckingRat/RatPoison#396]
![Screenshot (324)](https://user-images.githubusercontent.com/65115405/81497909-39f11d80-92f4-11ea-94c9-d49eebd856e8.png)

**Comment by matt1tk** [comment]
Issue with the JDK not downloading. 
$url = "http://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.msi Download this and run it, make sure to enable home variable.
