### ISSUE TITLE
Did everything, still black screen overlay

### ISSUE THREAD

**Issue by stabzter** [TheFuckingRat/RatPoison#405]
Installed Java with the build file, have win10, csgo running on borderless, built successfully, can hear the game but seeing black screen. Help ? xD
![dddd](https://user-images.githubusercontent.com/65963486/82912811-cd218880-9f6d-11ea-9419-28f7c553996b.png)

**Comment by Rubin-Paudel** [comment]
I have the same problem

**Comment by matt1tk** [comment]
#147 and #136 both address your issue
