### ISSUE TITLE
Stuck on launching

### ISSUE THREAD

**Issue by memecida** [TheFuckingRat/RatPoison#411]
Hey there. I was using ratpoison without any problems until the release of the new csgo patch.
Now it shows:
"Launching..." even thought I've enabled DEBUG on the config, it doesn't show anything else. I've already tried launching it as admin.
Does someone knows how to fix it?

**Comment by memecida** [comment]
DEBUG = true
MENU = true
MENU_KEY = 112
MENU_APP = "Counter-Strike: Global Offensive"
MENU_STAY_FOCUSED = true
OVERLAY_WIDTH = 1920
OVERLAY_HEIGHT = 1080

Some configs, if it will help.

**Comment by sotakoira** [comment]
download the fix version and build it again

**Comment by phooooon** [comment]
no longer working for some reason

**Comment by phooooon** [comment]
> download the fix version and build it again

where is it?

**Comment by dayz2000** [comment]
1.delete old build folder
2.download new src/main
3.start build.bat
4.enjoy it
