### ISSUE TITLE
still undetected todays update ?

### ISSUE THREAD

**Issue by dayz2000** [TheFuckingRat/RatPoison#412]
still safety？

**Comment by rat-star** [comment]
anybody having overlay initializing issue? cant get this new update to work

**Comment by dayz2000** [comment]
> anybody having overlay initializing issue? cant get this new update to work

1.delete old build folder
2.download new src/main
3.start build.bat
4.enjoy it

**Comment by rat-star** [comment]
i downloaded the completely new 1.6 fix update just unable to overlay into CS....

**Comment by dayz2000** [comment]
> 我下载了全新的1.6修复程序更新，只是无法覆盖到CS中。

you have delete old ver's and build new

**Comment by matt1tk** [comment]
Still undetected, but obviously can change
