### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by phooooon** [TheFuckingRat/RatPoison#413]
after todays update

**Comment by M1XT3NZ** [comment]
you need to redownload because csgo changed the "client_panorama.dll" back to "client.dll"

**Comment by rat-star** [comment]
i redownloaded it. cant work too

**Comment by dayz2000** [comment]
1.delete old build folder
2.download new src/main
3.start build.bat
4.enjoy it

**Comment by phooooon** [comment]
> 1.delete old build folder
> 2.download new src/main
> 3.start build.bat
> 4.enjoy it

Currently building. Hope it works

**Comment by rat-star** [comment]
> > 1.delete old build folder
> > 2.download new src/main
> > 3.start build.bat
> > 4.enjoy it
> 
> Currently building. Hope it works

keep us updated

**Comment by phooooon** [comment]
> > > 1.delete old build folder
> > > 2.download new src/main
> > > 3.start build.bat
> > > 4.enjoy it
> > 
> > 
> > Currently building. Hope it works
> 
> keep us updated

Thanks brother. Working
