### ISSUE TITLE
[WINDOWS 10] RatPoison is not working

### ISSUE THREAD

**Issue by qvkhan** [TheFuckingRat/RatPoison#416]
Hello !

Last night, RatPoison was working well, but today, i don't know why when i run the Start RatPoison 1.5.5.1.bat its stuck like that:

![notworking](https://user-images.githubusercontent.com/66433657/83786001-677e7c00-a692-11ea-8894-6ddaa1554712.png)

"Loading settings...
Settings loaded
Launching..."

So i wait few minuts and then I decide to delete RatPoison, Steam and CSGO (completely deleting the software the cheat and the game), I restart my computer and reinstall everything and it's still stuck at Launching... this is crazy i tried everything (the Run as Administrator and stuff and still not working can you help me please ? 
I have been using this cheat for 2 years.

Thank you guys.

**Comment by TheFuckingRat** [comment]
I suggest you join the discord, I made an announcement about this. The issue has been fixed on both the master and beta branch, just redownload from github.

**Comment by WikeMill69** [comment]
im having the same issue, i just deleted RatPoison and reinstalled it and still no fix ;/

**Comment by rahulalwaysrite** [comment]
discord channel ? invite orl ink

**Comment by matt1tk** [comment]
J2uHTJ2

**Comment by groks06** [comment]
Hi i need some help
"""""""Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.""""""""
I don't how to use it pls help me

**Comment by matt1tk** [comment]
Watch the video linked in the github.
