### ISSUE TITLE
Stuck at Launching...

### ISSUE THREAD

**Issue by Benjjiyy** [TheFuckingRat/RatPoison#419]
![image](https://user-images.githubusercontent.com/66467596/83859326-0a300c80-a71e-11ea-949f-9b2cb581c81a.png)
What do i do?
Java version: ( openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing) )

**Comment by sotakoira** [comment]
download the fixed version and build that, game update broke all existing versions of this cheat.
