### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Matsuri233** [TheFuckingRat/RatPoison#420]
![20200605192945](https://user-images.githubusercontent.com/55996342/83871631-f78bf680-a762-11ea-9e00-5e35f9801a4e.png)

**Comment by Matsuri233** [comment]
1.6 can build sucessfully, but 1.7 failed

**Comment by matt1tk** [comment]
Seems like an internet issue.

**Comment by Matsuri233** [comment]
![20200606093516](https://user-images.githubusercontent.com/55996342/83933197-10cf8a00-a7d9-11ea-9fec-67ec4eb9567d.png)
a new problem

**Comment by matt1tk** [comment]
It’s a network problem. Has nothing to do with ratpoison.
