### ISSUE TITLE
Can we get Ratpoison 1.5.4.1 to work again?

### ISSUE THREAD

**Issue by sofiadif** [TheFuckingRat/RatPoison#427]
1.6 is a real downgrade when it comes to legit aimbot (also 'name esp' don't work). its probably great if you wanna rage and get OW banned

Would love if someone upload the version before 1.6 and make it work to the new csgo update. Or maybe tell us how to fix it ourself.. **Thanks**

**Comment by retart1337** [comment]
Fixed 1.5.4 source code
https://mega.nz/file/yMlw3CqC#BymMXneNofSrjhfXYVMFb9v6KROM1FHSLusJnh8-eCc

**Comment by matt1tk** [comment]
You can download from github, scroll through commits to find version you want. I think this is it: https://github.com/TheFuckingRat/RatPoison/tree/4726c104527cdc746c58d4f53ad1ccf790c2ea10

Just click download and build. however it will not work unless you change this line, THEN build it: 

https://github.com/TheFuckingRat/RatPoison/commit/2ba842a8720301c8e717b2c3d4fd413bd8b89216
