### ISSUE TITLE
task :compileKotlin FAILED

### ISSUE THREAD

**Issue by Skymarek** [TheFuckingRat/RatPoison#434]
![image](https://user-images.githubusercontent.com/66534513/83954154-ea483800-a846-11ea-8839-0fb18e6f8843.png)
                                            i need help pls

**Comment by retart1337** [comment]
do you have JDK installed?

**Comment by matt1tk** [comment]
Maybe... type Y when it asks to install the JDK???? There's a video tutorial for a reason

**Comment by Skymarek** [comment]
jdk is installed ;c
