### ISSUE TITLE
It says Launching... but its not opening.

### ISSUE THREAD

**Issue by lilwhessie** [TheFuckingRat/RatPoison#436]
hey i was using this cheat perfectly for 1 or 2 months than i went a trip, after 2 weeks i tried to open it again but it says 
Loading settings...
Settings loaded
Launching...
but nothing happens. What happened i dont know, can someone help?

**Comment by sotakoira** [comment]
you have to rebuild the latest master or beta to fix this, update from 4th june changed name of client_panorama.dll module

**Comment by lilwhessie** [comment]
i changed and tried but didnt work the first time but now as you said i rebuild it now it works thanks man you got big dick

**Comment by lilwhessie** [comment]
F1 button fixed as well. it wasnt working before update.
