### ISSUE TITLE
Alright, I listened to you but STILL.

### ISSUE THREAD

**Issue by Skymarek** [TheFuckingRat/RatPoison#437]
![image](https://user-images.githubusercontent.com/66534513/83962670-97e73580-a89f-11ea-8920-60da46981dcb.png)
 I am honestly confused

**Comment by Skymarek** [comment]
and yes i have JDK installed

**Comment by Skymarek** [comment]
java development kit 8

**Comment by sotakoira** [comment]
uninstall every jdk/jre you have and install jdk 14.0.1 from oracles site

**Comment by matt1tk** [comment]
Open the .ps1 file in notepad, change "https" to "http". This is a network issue on your end however.

@sotakoira I don't recommend installing Oracle's JDK, worst case just install OpenJDK from the website. Oracle JDK takes command line flags that are not in the latest version
