### ISSUE TITLE
error installing JDK

### ISSUE THREAD

**Issue by Tig3R105** [TheFuckingRat/RatPoison#439]
Hi I get this error message when i try to download JDK while building it,  

Install JDK (required)? [Y/N] y
Downloading JDK...
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At D:\random apps\CSGO programs\RatPoison-master\build.ps1:4 char:1
+ $wc.DownloadFile($url, $output)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Installing JDK...
Building RatPoison...
> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files (x86)\Java\jre1.8.0_251' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

When i try to download JDK manually the build.bat cannot find it and says i only have JRE.

Any help would be much appreciated, Thanks!

**Comment by matt1tk** [comment]
Open the .ps1 file in notepad, change "https" to "http". This is a network issue on your end however
