### ISSUE TITLE
1.5.4 Crash the second i turn on "Box" Name ESP

### ISSUE THREAD

**Issue by EmaAfk** [TheFuckingRat/RatPoison#460]
Would appreciate any fix for this - I know 1.7 exists, But a lot of users dont like the change of the aim on 1.6 and 1.7
This:

> Exception in thread "DefaultDispatcher-worker-1" java.lang.IndexOutOfBoundsException: Bounds exceeds available space : size=45932, offset=45948
>         at com.sun.jna.Memory.boundsCheck(Memory.java:220)
>         at com.sun.jna.Memory.getInt(Memory.java:484)
>         at rat.poison.game.entity.PlayerKt.armor(Player.kt:64)
>         at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt:90)
>         at rat.poison.scripts.esp.BoxESPKt$boxEsp$1.invoke(BoxESP.kt)
>         at rat.poison.App.render(RatPoison.kt:292)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
>         at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
>         at rat.poison.RatPoison$main$1.invokeSuspend(RatPoison.kt:124)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)

**Comment by retart1337** [comment]
Fix the source code
https://github.com/TheFuckingRat/RatPoison/commit/be9eed4a9e4996ca1589273bbef8b056c6fe660f
