### ISSUE TITLE
Beta building error

### ISSUE THREAD

**Issue by phooooon** [TheFuckingRat/RatPoison#467]
If i press yes for jdk install
`Install JDK (required)? [Y/N] y
Downloading JDK...
& : The term './build.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:3
+ & './build.ps1'
+   ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./build.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Installing JDK...
Building RatPoison...
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

If there is an error message, close this window, try rebuilding a few times, then make a github issue if it continues.

Would you like to randomize the file name for safety? [Y/N]
`

if i press no
`Install JDK (required)? [Y/N] n
Okay :)
Building RatPoison...
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

If there is an error message, close this window, try rebuilding a few times, then make a github issue if it continues.

Would you like to randomize the file name for safety? [Y/N]`

**Comment by matt1tk** [comment]
Download and run this: http://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.msi 

that's all that the ps1 does anyway, not sure why it doesn't run on your pc.

**Comment by retart1337** [comment]
Also delete this line:
https://github.com/TheFuckingRat/RatPoison/blob/c683695fd15bd4b62a8d7894ce1f82b4c8ef1d70/build.bat#L11
from your build.bat file
