### ISSUE TITLE
Force aim shakes the screen

### ISSUE THREAD

**Issue by r0ot7** [TheFuckingRat/RatPoison#472]
Enabling force aim shakes the screen a lot.

![2020-06-18 14_01_49-Rat Poison UI](https://user-images.githubusercontent.com/66738307/85002660-cbb13d80-b172-11ea-916d-1364d52b57e0.png)

**I am not moving the mouse at all**

![ezgif com-crop (1)](https://user-images.githubusercontent.com/66738307/85007001-8859cd80-b178-11ea-8b46-9ad357fdf50d.gif)

**Comment by matt1tk** [comment]
Make sure you set your mouse sensitivity correctly.

**Comment by TheFuckingRat** [comment]
The latest beta build should set sensitivity for you again
