### ISSUE TITLE
Build.ps1 error

### ISSUE THREAD

**Issue by brache15** [TheFuckingRat/RatPoison#474]
![image](https://user-images.githubusercontent.com/67181180/85193401-9275ec00-b29e-11ea-84b2-20e5c0d7dd0a.png)

I'm having this error when I open the build.bat, try it like 10 times and it's still the same, delete and re-download and it's still the same error. 

If I choose N instead of Y, it stays in building ratpoison.

I don't know what to do, I have multiple errors when I try to build it

**Comment by matt1tk** [comment]
This has been asked. #467
