### ISSUE TITLE
Launching...

### ISSUE THREAD

**Issue by LukaGogilashvili** [TheFuckingRat/RatPoison#475]
Hello, whenever i try to run the batch file it stucks on Launching... i've been waiting for minutes but its doesnt seem to be working. my device is win 10 pro x64
 any solutions? 
![image](https://user-images.githubusercontent.com/47856237/85200494-f3d2a500-b308-11ea-9275-2a755b6cb4ba.png)

**Comment by retart1337** [comment]
Update to 1.7
