### ISSUE TITLE
Wont build

### ISSUE THREAD

**Issue by Rhotoice** [TheFuckingRat/RatPoison#482]
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
Press any key to continue . . .
  

how do i fix.

**Comment by retart1337** [comment]
Install JDK
http://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13.0.2%2B8/OpenJDK13U-jdk_x64_windows_hotspot_13.0.2_8.msi
