### ISSUE TITLE
RIP Ratpoison?

### ISSUE THREAD

**Issue by dacryphiliac** [TheFuckingRat/RatPoison#486]
Did the new update permanently destroy this cheat?

**Comment by retart1337** [comment]
Still works

**Comment by r0ot7** [comment]
> Still works

Until beta is pushed to public release.

**Comment by r0ot7** [comment]
> Did the new update permanently destroy this cheat?

Not just this cheat, every cheat read the information from DLLs; I think every cheat will suffer the consequences, until they find a way to bypass the authorization for DLLs.

**Comment by retart1337** [comment]
Ratpoison don't read the information from dll lmao

**Comment by r0ot7** [comment]
> Ratpoison don't read the information from dll lmao

okay.
What ever it does using those DLL.

**Comment by retart1337** [comment]
Ratpoison does nothing with dlls

**Comment by retart1337** [comment]
Give me exact line where ratpoison uses dll

**Comment by retart1337** [comment]
For examlle
https://github.com/TheFuckingRat/RatPoison/blob/453ad33935001da96399a91a0e3b390a7b287b55/src/main/kotlin/rat/poison/game/entity/Entity.kt#L46
this is reading from memory

**Comment by monkeyscout** [comment]
The only solution is to wait for the official release since Valve may update their program due to complains from the beta.  If it gets detected than RIP

**Comment by lvozab** [comment]
> 
> 
> Ratpoison does nothing with dlls

> 
> 
> Give me exact line where ratpoison uses dll

I'm not an expert in creating cheats, so I'll leave this up to you, but what about one of the latest commits https://github.com/TheFuckingRat/RatPoison/commit/2ba842a8720301c8e717b2c3d4fd413bd8b89216? At that time the cheat stopped working because Valve changed the filename of one DLL. What is the cheat doing with the DLLs, then?

**Comment by r0ot7** [comment]
> Give me exact line where ratpoison uses dll

**The defined constant**
https://github.com/TheFuckingRat/RatPoison/blob/453ad33935001da96399a91a0e3b390a7b287b55/src/main/kotlin/rat/poison/settings/SetVars.kt#L32

which is under _C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\bin_

**Got the instance**
https://github.com/TheFuckingRat/RatPoison/blob/453ad33935001da96399a91a0e3b390a7b287b55/src/main/kotlin/rat/poison/game/CSGO.kt#L56


**Using the instance (2 of 73 instances xD)**

https://github.com/TheFuckingRat/RatPoison/blob/453ad33935001da96399a91a0e3b390a7b287b55/src/main/kotlin/rat/poison/scripts/KnifeBot.kt#L125

https://github.com/TheFuckingRat/RatPoison/blob/453ad33935001da96399a91a0e3b390a7b287b55/src/main/kotlin/rat/poison/game/entity/Player.kt#L49

**Comment by matt1tk** [comment]
that's it reading client dlls, not injecting DLL's. the update does NOT affect ratpoison.
