### ISSUE TITLE
it's possible to add third-person feature?

### ISSUE THREAD

**Issue by dayz2000** [TheFuckingRat/RatPoison#490]
it's possible ?

**Comment by retart1337** [comment]
Possible, but you can't rotate camera and exit it until you die

**Comment by sidekek** [comment]
iirc you can write to iObserverMode to get a shitty thirdperson.

**Comment by matt1tk** [comment]
> 
> 
> iirc you can write to iObserverMode to get a shitty thirdperson.

Yeah I found that but as mentioned it won't let you exit it or rotate or anything? seems kinda shitty. if there's no other way to do it I'd rather not add it.

**Comment by sidekek** [comment]
> 
> 
> > iirc you can write to iObserverMode to get a shitty thirdperson.
> 
> Yeah I found that but as mentioned it won't let you exit it or rotate or anything? seems kinda shitty. if there's no other way to do it I'd rather not add it.

the camera issue is only for custom maps, but I agree that there is no real point unless it's done properly.
