### ISSUE TITLE
can anybody tell me what is perfect bomb defuse???

### ISSUE THREAD

**Issue by mountaincastle47** [TheFuckingRat/RatPoison#502]
and how to use it?????

**Comment by sotakoira** [comment]
look at the bomb and cheat will defuse it at 10 or 5 secs depending if you have a kit, it's a flex feature to show you have cheats.

https://streamable.com/3v0rjx

**Comment by mountaincastle47** [comment]
> k at the bomb and cheat will defuse it at 10 or 5 secs depending if you have a kit, it's a flex feature to show you have cheats.

thanks :D
