### ISSUE TITLE
CS NEW Trusted Mode

### ISSUE THREAD

**Issue by oofool** [TheFuckingRat/RatPoison#507]
Anyone tried using it  after the update? Still working and undetected?

**Comment by mountaincastle47** [comment]
Idk yet

**Comment by crossroaddemon** [comment]
i tried on workshop, it worked but idk if its still undetected or no.

**Comment by theunknowncodewizard** [comment]
Was playing 3 matches on casual today, working as always - don't know about detection status yet. 
Lets wait till tomorrow - will play one competitive soon - lets see! Fingers crossed 🤞

**Comment by dayz2000** [comment]
using trusted mode many days work well

**Comment by sotakoira** [comment]
Beta 1.7 works perfectly, don't know about 1.6 but should work too.
Some people had vac errors when queueing but restarting steam / not running the game in administrator mode fixes that.

**Comment by matt1tk** [comment]
works fine. rp is external
