### ISSUE TITLE
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_251' used by Gradle. Make sure Gradle is running on a JDK, not JRE

### ISSUE THREAD

**Issue by AintReady** [TheFuckingRat/RatPoison#516]
When ever I start build.bat I get 
Build Failed 
And this is a reason 
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_251' used by Gradle. Make sure Gradle is running on a JDK, not JRE

How to fix it

Please help

**Comment by retart1337** [comment]
> install JDK, no JRE
