### ISSUE TITLE
footstep and crosshair will show in discord streaming ?

### ISSUE THREAD

**Issue by dayz2000** [TheFuckingRat/RatPoison#523]
looks yes  that's weird

**Comment by siautalius** [comment]
No it doesnt show

**Comment by dayz2000** [comment]
> No it doesnt show

but when im streaming my friends say they can see footstep and crosshair

**Comment by matt1tk** [comment]
Discord streaming gets your whole screen AFAIK. disable all visuals. If it was OBS or nvidia shadowplay + no desktop capture, overlay features would work. but discord stream records whole screen
