### ISSUE TITLE
Status check

### ISSUE THREAD

**Issue by oofool** [TheFuckingRat/RatPoison#528]
Still working and undetected after recent update?

**Comment by sotakoira** [comment]
undetected and new-testing works soooooo good.

**Comment by retart1337** [comment]
![image0-1-1](https://user-images.githubusercontent.com/48867150/88426364-bc6c8200-cdf9-11ea-9fdb-d52fe06e259b.png)

**Comment by matt1tk** [comment]
stop making status checks just don't use it on any acc you care about
