### ISSUE TITLE
not work anymore new test

### ISSUE THREAD

**Issue by dayz2000** [TheFuckingRat/RatPoison#541]

**Comment by siautalius** [comment]
either give more information or redownload

**Comment by dayz2000** [comment]
> either give more information or redownload

i try rebuild but not work 

new test
beta
all not work

**Comment by siautalius** [comment]
old versions crashed csgo and the cheat. Try to redownload

**Comment by dayz2000** [comment]
> old versions crashed csgo and the cheat. Try to redownload

redownload still not work 
you work well ?

**Comment by GreenMan36** [comment]
Give more info about why it isn't building.

**Comment by dayz2000** [comment]
> Give more info about why it isn't building.

well it's auto fix when i restart PC ........
dont know what happen
