### ISSUE TITLE
Opening menu in Buy zone automatically buys weapons

### ISSUE THREAD

**Issue by alexPNG** [TheFuckingRat/RatPoison#80]
Whenever I open the menu while in the buy zone it will automatically buy random weapons, sometimes it doesn’t but it occurs a lot. Couldn’t find an option to disable this in case it is a feature but decided to feedback on it just in case.

**Comment by suciuale** [comment]
disable rapid fire

**Comment by TheFuckingRat** [comment]
This isn't happening for me... with or without automatic weapons, make sure F1 isnt bound to autobuy/fullbuy in settings? Or whatever your menu key is
