### ISSUE TITLE
'java' is not recognized as an internal or external command, operable program or batch file. Press any key to continue . . .

### ISSUE THREAD

**Issue by Usernameistakensad** [TheFuckingRat/RatPoison#81]
In the newest version when i run the bat file it just says 'java' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

If you know the fix for this if its on my side could you share it?

**Comment by Usernameistakensad** [comment]
https://gyazo.com/ff1109d27b17a4b191a6b5390c68aff1

**Comment by Usernameistakensad** [comment]
Ok figured it out For anyone that has this bug just open the bat file and remove the first line set path="%JAVA_HOME%";%path% and it fixes it.

**Comment by TheFuckingRat** [comment]
Seems like java_home isn't set correctly, works fine for me when its set to jdk12

**Comment by jwao** [comment]
> Ok figured it out For anyone that has this bug just open the bat file and remove the first line set path="%JAVA_HOME%";%path% and it fixes it.

what bat file?
