### ISSUE TITLE
black screen in win10

### ISSUE THREAD

**Issue by GIGIGIVEVEH** [TheFuckingRat/RatPoison#83]
im sorry ,but win10 still just a black screen .
my win10 version is 64-17763.
ps: waller and aim works but covered by the black screen.

**Comment by TheFuckingRat** [comment]
Overlay doesn't work on CSGO is fullscreen, only windowed/borderless. If this isn't the case I need more information

**Comment by GIGIGIVEVEH** [comment]
> Overlay doesn't work on CSGO is fullscreen, only windowed/borderless. If this isn't the case I need more information
Thank you for replying to me. I used your program on win8 and win10 before, win8 does not show overlay but can waller. Win10 is a black screen. I tried a variety of screen sizes, full screen, no borders, all the same. This time I reinstalled the system, the version is what I said before, the same is the overlay black screen. Can you tell me what information you need, I can provide it as much as possible.

**Comment by TheFuckingRat** [comment]
When using jdk 1.8 the overlay would launch as a black screen and not go transparent and ontop of csgo, but with jdk 12 it worked fine again. Try using 12 and see if that helps

**Comment by GIGIGIVEVEH** [comment]
Very embarrassing, same with JDK12, I guess maybe it is my system problem. What is your system version? Mine is 1809.
Ps: when the Hx running 
1 App Title: Counter-Strike: Global Offensive
2 WARNING: An illegal reflective access operation has occurred
3 WARNING: Illegal reflective access by org.lwjgl.system.MemoryAccess (file:/D:/Apps/HACK/RatPoison-master/build/RatPoison%201.3.3/RatPoison%201.3.3.jar) to field java.nio. Buffer.address
4 WARNING: Please consider reporting this to the maintainers of org.lwjgl.system.MemoryAccess
5 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
6 WARNING: All illegal access operations will be denied in a future release
7 Waiting for App
8 Initializing overlay **(*** Is this right? Or should there be a “success”/"overlay Initialized"? ***)**

**Comment by GIGIGIVEVEH** [comment]
by the way, there used to be a version. Although I can't see the overlay, I can use other functions, such as aimassistant, ESP, etc. I can also set the parameters, but I have to switch to the game again with F1.
Maybe this is my destiny XD.

**Comment by Infinity31337** [comment]
Have the same issue. JDK 12 with Windows 10. Only shows black screen as the overlay.

**Comment by GIGIGIVEVEH** [comment]
> Have the same issue. JDK 12 with Windows 10. Only shows black screen as the overlay.

All the functions work fine，just can't go transparent. Bad luck, we can only rely on the real ability.

**Comment by TheFuckingRat** [comment]
Type 'java -version' in cmd and see what version is running, it was a black screen for me when I was using 1.8, but 12.0.1 works fine for me

**Comment by GIGIGIVEVEH** [comment]
> Type 'java -version' in cmd and see what version is running, it was a black screen when I was using 1.8, but 12.0.1 works fine for me

C:\Users\Administrator>java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
Booom (lll￢ω￢)

**Comment by TheFuckingRat** [comment]
Is there a difference running the bat vs the jar itself?

**Comment by GIGIGIVEVEH** [comment]
> Is there a difference running the bat vs the jar itself? Im on the same windows version btw, I never addressed it earlier


C:\Users\Administrator>java -jar "D:\Apps\HACK\RatPoison-master\build\RatPoison 1.3.3\RatPoison 1.3.3.jar"
Exception in thread "main" java.lang.IllegalStateException: File(fileDir).listFiles() must not be null
        at rat.poison.RatPoison.loadSettingsFromFiles(RatPoison.kt:122)
        at rat.poison.RatPoison.loadSettingsFromFiles$default(RatPoison.kt:109)
        at rat.poison.RatPoison.main(RatPoison.kt:46)
        at rat.poison.RatPoison.main(RatPoison.kt)

Nothing happened. Is it possible that some other plugins are needed？ Like OpenGL or DX9？This system is new . I have almost nothing installed, except for the JDK and the default plugin.

**Comment by TheFuckingRat** [comment]
Why are you using 1.3.3?

**Comment by GIGIGIVEVEH** [comment]
> Why are you using 1.3.3?

Forgot to update. Just tried the latest one 1.3.4. Same black screen. But i think this has little to do with the version , because it is also a black screen in earlier versions(all latest one). Will it be that the graphics card is not supported? Nvidia 980M. Do I need to install some other running environment?

**Comment by GIGIGIVEVEH** [comment]
> Why are you using 1.3.3?

I plan to reinstall my system and try it again. By the way, is charlatano still undetected? I used it vs bot, no blackscreen and no esp,etc ,only aimassistant works fine.

**Comment by Infinity31337** [comment]
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

Reinstalled Java 12. Now F1 just throws me to the desktop ;(

**Comment by TheFuckingRat** [comment]
@Infinity31337 if you're fullscreen it will open on the desktop, overlay only works windowed/borderless, otherwise there shouldnt be a problem. @GIGIGIVEVEH I reinstalled windows within the past week, and haven't had an issue so I would assume it's an error on your side.

**Comment by GIGIGIVEVEH** [comment]
> @Infinity31337 if you're fullscreen it will open on the desktop, overlay only works windowed/borderless, otherwise there shouldnt be a problem. @GIGIGIVEVEH I reinstalled windows within the past week, and haven't had an issue so I would assume it's an error on your side.

Definitely it's on my side ;D. Would u like to send me your windows copy or tell me where to download. My copy isn't a pure version, i downloaded it on a pirated software website.

**Comment by TheFuckingRat** [comment]
You can download a windows 10 iso directly from Microsoft's website, and I'd guess resetting your PC would use a correct version as well.

**Comment by GIGIGIVEVEH** [comment]
> You can download a windows 10 iso directly from Microsoft's website, and I'd guess resetting your PC would use a correct version as well.

And I only need to install Jdk12 again, right? Win10 seems like have DX12 and .NET itself.

**Comment by TheFuckingRat** [comment]
As far as I know thats all I installed and it worked for me

**Comment by GIGIGIVEVEH** [comment]
> As far as I know thats all I installed and it worked for me

idk why I can't install jdk 12, but I downloaded rat1.3.4 before, now it works very very gooooood. thx bro.
