### ISSUE TITLE
Skeleton and Box ESP is not aligned with the models.

### ISSUE THREAD

**Issue by Google407** [TheFuckingRat/RatPoison#86]
![glitch](https://user-images.githubusercontent.com/52907667/61198955-a6b87d00-a70e-11e9-83c6-fe9ffc7d7414.png)

**Comment by TheFuckingRat** [comment]
Borderless or windowed? I'm assuming borderless

**Comment by Google407** [comment]
Fullscreen Windowed

**Comment by TheFuckingRat** [comment]
Latest hotfix should fix the issue, close the issue if it does, if not comment again
