### ISSUE TITLE
Bhop bug

### ISSUE THREAD

**Issue by Soulhackzlol** [TheFuckingRat/RatPoison#87]
idk if you can fix this : when im in the console , typing on chat... the bhop jumps .
know that c++ cheats have fix this . 
TY for your awesome work!

**Comment by Google407** [comment]
Yea, this happens to me as well.

**Comment by Soulhackzlol** [comment]
oh and sometimes the bhop dosnt work...

**Comment by uniarch** [comment]
> 
> 
> Oh, and sometimes the bhop doesn't work... P.D: when it doesn't work you have to jump one more time and it work. but when the player is falling its probable that bhop is not going to work

did you unbind space key?

**Comment by Soulhackzlol** [comment]
> > Oh, and sometimes the bhop doesn't work... P.D: when it doesn't work you have to jump one more time and it work. but when the player is falling its probable that bhop is not going to work
> 
> did you unbind space key?

nope , i dont want to jump with scroll =(

**Comment by uniarch** [comment]
you will jump with a space key. (when using the cheat and bhop on)

**Comment by TheFuckingRat** [comment]
It checks if the mouse is locked or not, so it shouldn't jump in chat, but it might be delayed. With bhopping sometimes not working, there isn't anything I can really change, if you hold the spacebar from when you start jumping it should work, don't hit space bar to jump initially, let go, and then start holding it again.
