### ISSUE TITLE
Settings not saved in 1.3.4

### ISSUE THREAD

**Issue by rattedpojzn** [TheFuckingRat/RatPoison#88]
I noticed that the aim settings aren't saved when you make a config, nor when you load it. I didn't confirm it, but I think even closing the menu will reset the FOV, not sure about the other sliders.

Also, the Bomb Timer opacity is not saved.

**Comment by TheFuckingRat** [comment]
Bomb Timer & Spectator List position and opacity isn't being saved atm, however normal settings are saving and loading just fine, are you sure that the aim settings you're changing, that you're not overriding without enabling the override for that specific gun? As an example with the default settings, I can go to Rifles, and select AK47, enable override isn't checked to begin with, I can check the initial 'Weapon Override' to view the default override settings, and I can change those variables around, but if I don't check 'Enable Override' those settings wont save, and when reopening the menu or a config, those settings will go back to default.

**Comment by rattedpojzn** [comment]
I apologize about the error. I noticed it the middle of a game, and didn't try it after. I think the Weapon Override was indeed enabled, noticed that it carries over to the other weapon types, hence the default values for all of them.

Also, not sure if intentional, but the Speed Delay for some weapons is over the max slider value of 5ms.

**Comment by TheFuckingRat** [comment]
Yeah I figured, i changed default values around and didn't get around to fixing the overrides and other defaults
