### ISSUE TITLE
No Ingame Menu

### ISSUE THREAD

**Issue by Wavy-Waves** [TheFuckingRat/RatPoison#91]
Finished loading settings
Launching... 

That is the message I get when I open the bat file. Any fix for this?

**Comment by Wavy-Waves** [comment]
I'm running JDK 8, 12 doesn't seem to want to work. I've tried debug and it didn't help any.

**Comment by TheFuckingRat** [comment]
Set DEBUG = true in general.kts, and see if it outputs anything different, also I'm no longer testing with 8, 12 is the only one being supported atm, so I'd suggest getting it to work. Also refer to the solution in https://github.com/TheFuckingRat/RatPoison/issues/84 as it could be your issue as well.

**Comment by Wavy-Waves** [comment]
I got 12 to work, somehow, and the cheat works fine. Is there a way to use any other fullscreen option than fullscreen windowed? I usually play 4:3 and I'm getting 50 fps.

**Comment by Wavy-Waves** [comment]
Other than fps issues, everything is working fine.

**Comment by TheFuckingRat** [comment]
Many options work without the menu, you can disable the menu if you want in general.kts, you can also draw the menu on a blank notepad or another application, and then just alt tab to use the menu. But no there is no way to draw the overlay on CSGO while fullscreen.
