### ISSUE TITLE
Feature request/Bug?: add delay before shot

### ISSUE THREAD

**Issue by uniarch** [TheFuckingRat/RatPoison#93]
For onetaps. I have tried AUTO_WEP_DELAY adjusting but did not work for me
![image](https://user-images.githubusercontent.com/20053715/61642984-9f631780-acaa-11e9-9d69-ce1343ef5cbc.png)
Would like to have Shotdelay feature like most internal cheats do

offtopic: the best legit cheat I have ever used(compared to paid also) and doesnt drain my fps

**Comment by TheFuckingRat** [comment]
Auto wep delay is for the automatic weapons check box on the aim tab, its essentially auto pistol but works for shotguns and shit as well. The bone trigger has it's own delay as well, and I don't really see a point in adding a delay to the normal aimbot, just don't click as fast?

**Comment by mattbot101** [comment]
Either way, aimbot does have a delay, right? "Aimbot delay" or something in the ingame menu?

**Comment by uniarch** [comment]
> 
> 
> Auto wep delay is for the automatic weapons check box on the aim tab, its essentially auto pistol but works for shotguns and shit as well. The bone trigger has it's own delay as well, and I don't really see a point in adding a delay to the normal aimbot, just don't click as fast?

I don't use separate key to aim so I would like aimbot would work sometime before shooting the first bullet to aim at the guy and land a shot on the model not in the air

**Comment by TheFuckingRat** [comment]
@uniarch I understand, might not come in the very next update but will be put on the todo.

**Comment by uniarch** [comment]
Didn't you forget about it?( So many updates came
