### ISSUE TITLE
HELP Kotlin scriptenginefactory error when running start bat file 

### ISSUE THREAD

**Issue by ajpad** [TheFuckingRat/RatPoison#97]
I am getting the following error when I try running the start.bat file. I have made sure JRE and JDK are installed and the correct paths are there. I ran the start.bat after loading into a game. I would really appreciate help!

script engine manager providers.next() javax.script.scriptenginefactory: provider .org.jetbrains.kotlin.script.jsr223.kotlinjsr223Jvmlocalscriptenginefactory not found
Exception in thread “main” java.lang.nullpointerexception
At com.charlatano.charlatano.loadsettings(charlatano.kt:88)
At com.charlatano.charlatano.main(charlatano.kt:40)

**Comment by TheFuckingRat** [comment]
These issues are for ratpoison, not charlatano.
