### ISSUE TITLE
UI Not working

### ISSUE THREAD

**Issue by Frasski** [TheFuckingRat/RatPoison#98]
When I launch it, It's just black. Help?

**Comment by TheFuckingRat** [comment]
What jdk

**Comment by GIGIGIVEVEH** [comment]
reinstall win10 1903 and jdk 12.0.1 black screen solved.

**Comment by Frasski** [comment]
> What jdk

**jdk1.8.0_211**

**Comment by uniarch** [comment]
update to jdk 12 then?

**Comment by Frasski** [comment]
> update to jdk 12 then?

I did but the JDK 12 doesn't even have tools.jar in it so I literally can't use it to compile RatPoison

**Comment by TheFuckingRat** [comment]
Jdk 12 works fine, it's something wrong on your end, google any error you get, info on installing the jdk/setting java_home is available near the bottom of the readme
