### ISSUE TITLE
set "head" aim at neck,set "neck" aim at chest,crosshair will shift downward

### ISSUE THREAD

**Issue by GIGIGIVEVEH** [TheFuckingRat/RatPoison#99]
Although it does not affect the use，it also means trigger cant make headshot.

**Comment by TheFuckingRat** [comment]
Im not sure what this is supposed to be about... when bone is head it aims at the head for me, same for neck aiming at neck, etc. Enabling bone trigger and its aim, it aims at right bone for the weapon selected. The only issue I've seen is nearest aims at the neck instead of the head
